#!/bin/bash

function readFile {
	if [ -f "$1" ]; then
		. "$1"
	else
		echo "ERROR: File not found: $1"
	fi
}
bashFilesHome=$HOME/dev/cheatsheet/dotfiles/bash
if [ ! -d "$bashFilesHome" ]; then
	bashFilesHome=/h/dev/cheatsheet/dotfiles/bash
	echo "Trying to use alternative HOME: $HOME"
fi
readFile $bashFilesHome/env
readFile $bashFilesHome/config
readFile $bashFilesHome/aliases
