" behave mswin
behave xterm

" Initialization -------------------------------------------------------------
set nocompatible
"silent! call pathogen#infect()
call pathogen#infect()
silent! call pathogen#runtime_append_all_bundles()
"let mapleader = ","
"let mapleader = " "
set showcmd                     " display incomplete commands
set hidden                      " handle multiple buffers more efficiently
set laststatus=2                " show status line
set encoding=utf-8


" GUI only stuff -------------------------------------------------------------
if has('gui_running')
    " switch off the menu in the gui window
    "set guioptions=gt

    " horizontal scrollbar
    set guioptions+=b
endif

if has('mac')
elseif has('unix')
    set guifont=DejaVu\ Sans\ Mono\ 9
elseif has('win32')
    set guifont=Lucida_Console:h8:w5
endif
"set guifont=Monospace\ 9
"set guifont=Lucida_Console:h8:cDEFAULT
"set guifont=lucida_console:h8:w5
"set lines=64 columns=160

set cursorline          " highlight current line
"set linebreak			" TODO what is linebreak for?

"colorscheme default
"colorscheme darkblue
try
    "colorscheme evening
    "colorscheme vividchalk
    colorscheme wombat
    "colorscheme inkpot
catch
	"colorscheme slate
	colorscheme desert
endtry

set smartindent
"set autoindent

set tabstop=4
set expandtab                   " use spaces, not tabs
"set showtabline=2               " show the tabs right below the menu
set shiftwidth=4 softtabstop=4
set backspace=indent,eol,start  " backspace through everything in insert mode

"imap jj <Esc>
"imap :: <Esc>

" visualise a word and switch to insert mode
"map <space> viw
" visualise a word
"map <space> vw

" only for cheatsheet.html: jump to the 1st '#' character, then replace
" everything in the html tag with '# '
"map <F3> f#cit# 

" Use colours that work well on a dark background (Console is usually black)
"set background=dark

" Show EOL type and last modified timestamp, right after the filename
set statusline=%<%F%h%m%r\ [%{&ff}]\ (%{strftime(\"%H:%M\ %d/%m/%Y\",getftime(expand(\"%:p\")))})%=%l,%c%V\ %P

" Here's the vimclojure stuff. You'll need to adjust the NailgunClient
" setting if you're on windows or have other problems.
"let vimclojure#FuzzyIndent=1
let vimclojure#HighlightBuiltins=1
let vimclojure#HighlightContrib=1
let vimclojure#DynamicHighlighting=1
let vimclojure#ParenRainbow=1
"let vimclojure#ParenRainbowColors = { '1': 'guifg=green' }
let vimclojure#WantNailgun = 1
let vimclojure#NailgunClient = "ng"  " the ng is already in env PATH
"let vimclojure#NailgunServer = "192.168.178.20"  " 127.0.0.1
let vimclojure#NailgunPort = "2113"
"let vimclojure#SplitPos = "right"        " open the split window on the right side
"let vimclojure#SplitSize = 80

" Shortcuts ------------------------------------------------------------------

" Press twice the <Leader> to exit insert mode without a manual <ESC> or <C-C>
imap <Leader><Leader> <ESC>l

" Character coding for empty characters
set listchars=tab:>-,eol:$,precedes:>,trail:_
" Set symbols for tabs like textmate

" Toggle hidden (empty) chars
nmap <Leader>l :set list!<CR>
"set list


" Toggle line wrapping
nmap <Leader>wr :set wrap!<CR>

" Save file
nmap <Leader>w :w<CR>

" Toggle line numbers
"nmap <Leader>n :set nu!<CR>

" ============================================================================
" try the shortcuts below:
" ============================================================================

" Quit the current window
nmap <Leader>q :q<CR>

" Delete the current buffer
nmap <Leader>bd :bd<CR>

" Show a list of all open buffers
"nmap <Leader>b :ls<CR>
map <Leader>b :TMiniBufExplorer<cr>

" Jump from window to window
nmap <Leader><Tab> <C-W>w

" Jump from tab to tab
nmap <Leader><S-Tab> :tabn<CR>

" Quickly 'maximize' a split - these shortcuts colide with VimClojure
"nmap <Leader>mw <C-W>\|
"nmap <Leader>mh <C-W>_
"nmap <Leader>me <C-W>=
"nmap <Leader>mm <Leader>mw<Leader>mh

" Quickly 'maximize' the entire UI - 999 is a bit lot :(
nmap <Leader>Mw :set columns=250<CR>
nmap <Leader>Mh :set lines=69<CR>
nmap <Leader>MM <Leader>Mw<Leader>Mh

" Split up/down/left/right
nmap <Leader>sk :sp \| Explore<CR>
nmap <Leader>sj :rightbelow sp \| Explore<CR>
nmap <Leader>sh :vsp \| Explore<CR>
nmap <Leader>sl :rightbelow vsp \| Explore<CR>

"nmap <Leader>er :tabnew ~/.vimrc<CR>
nmap <Leader>ev :e ~/.vimrc<CR>
nmap <Leader>ec :e ~/dev/cheatsheet/cheatsheet.html<CR>
" this vim-plugins shortcut may colide with something
nmap <Leader>ep :e ~/dev/cheatsheet/dotfiles/vim-plugins.sh<CR>
nmap <Leader>ea :e ~/dev/cheatsheet/dotfiles/bash/aliases<CR>
nmap <Leader>r :source ~/.vimrc<CR>
"nmap <Leader>rs :source ~/dev/mysite/mysession.vim<CR>
nmap <Leader>so :OpenSession<CR>
nmap <Leader>ss :SaveSession<CR>

" this is the default mouse setting
"if has('mouse')
"    set mouse=a
"endif


" Syntax ---------------------------------------------------------------------
syntax on
filetype plugin indent on
set showmatch
setlocal foldmethod=syntax
"set foldlevel=1
set foldlevelstart=99          "remove folds

"set linespace=4                "add some line space for easy reading


" Editor Behavior -------------------------------------------------------------
set wrap
set relativenumber       " Shows relative line numbers
"set number               " Shows line number
set showmode             " show the current mode
set ruler

" Searching
set hlsearch             " highlight matches
set incsearch            " incremental searching
set ignorecase           " searches are case insensitive...
set smartcase            " ... unless they contain at least one capital letter

" Backup files are for the weak
"set nobackup
"set nowritebackup

" Wait-time for a key code or mapped keysequence to complete, default 1000
"set timeoutlen=500

" Horizontal split
nmap <leader>- :sp<CR>
" Vertical split
"nmap <leader>\ :vsp<CR>

nmap <leader>cdf :color default<CR>:colorscheme default<CR>
nmap <leader>st :Gstatus<CR>
" <CR> allows me to use this shortcut from the :Gstatus window
nmap <leader>df <CR>:Gdiff<CR>
nmap <leader>gci :Gcommit<CR>
nmap <leader>gps :Git push<CR>

try                     " these keys are not mapped under windows by default
    unmap <S-Up>
    unmap <S-Down>
catch
endtry

nmap <S-Up> [e
nmap <S-Down> ]e

vmap <S-Left> <gv
vmap <S-Right> >gv
vmap <S-Up> [egv
vmap <S-Down> ]egv

" Remap 0 to first non-blank character
"map 0 ^

" Rename current file
function! RenameFile()
	let old_name = expand("%")
	let new_name = input('New file name: ', expand('%'))
	if new_name != '' && new_name != old_name
		exec ':saveas ' . new_name
		exec ':silent !rm ' . old_name
		redraw!
	endif
endfunction
map <leader>n :call RenameFile()<cr>

" use <leader>Ctrl+L to toggle the line number counting method
function! g:ToggleNuMode()
  if &nu == 1
     set rnu
  else
     set nu
  endif
endfunction
nnoremap <silent><leader><C-L> :call g:ToggleNuMode()<CR>

" Quickly switch buffers (prev/next)
" it doesn't work somehow TODO try to see why using :map or :nmap
"try
    "unmap <C-P>
    "unmap <C-N>
"catch
"endtry
"nmap <C-P> :bp<CR>
"nmap <C-N> :bp<CR>


if has('win32')
    nmap <leader>a :call Email("Andreas")<CR>
    nmap <leader>j :call Email("Jürgen")<CR>
    nmap <leader>y :call Email("Yvonne")<CR>
    nmap <leader>t :call Email("Thomas")<CR>
endif

nmap <leader>1 :1b<CR>
nmap <leader>2 :2b<CR>
nmap <leader>3 :3b<CR>
nmap <leader>4 :4b<CR>
nmap <leader>5 :5b<CR>
nmap <leader>6 :6b<CR>
nmap <leader>7 :7b<CR>
nmap <leader>8 :8b<CR>
nmap <leader>9 :9b<CR>

nmap <leader>01 :1b<CR>
nmap <leader>02 :2b<CR>
nmap <leader>03 :3b<CR>
nmap <leader>04 :4b<CR>
nmap <leader>05 :5b<CR>
nmap <leader>06 :6b<CR>
nmap <leader>07 :7b<CR>
nmap <leader>08 :8b<CR>
nmap <leader>09 :9b<CR>
nmap <leader>10 :10b<CR>
nmap <leader>11 :11b<CR>
nmap <leader>12 :12b<CR>
nmap <leader>13 :13b<CR>
nmap <leader>14 :14b<CR>
nmap <leader>15 :15b<CR>
nmap <leader>16 :16b<CR>
nmap <leader>17 :17b<CR>
nmap <leader>18 :18b<CR>
nmap <leader>19 :19b<CR>

autocmd BufRead,BufNewFile *.cljs setlocal filetype=clojure

" start maximized
if has('win32')
    au GUIEnter * simalt ~x
else
    " this works when gvim -c "call Maximize_Window()"
    function! Maximize_Window()
        silent !wmctrl -r :ACTIVE: -b add,maximized_vert,maximized_horz
    endfunction
endif

" Insure Clean Pasting w/autoindented code - this is probably not usefull
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>

" use <cword> to get the word under the cursor, and search for it in the
" current directory and all subdirectories; open the quickfix window when done
map <F4> :execute "vimgrep /" . expand("<cword>") . "/j **" <Bar> cwindow<CR>
nnoremap <F5> :GundoToggle<CR>
nnoremap <silent> <F9> :NERDTreeToggle<CR>
nnoremap <silent> <F11> :YRShow<CR>
"noremap <silent> <F12> :call VimCommanderToggle()<CR>
nmap <F12> :silent !google-chrome ~/dev/cheatsheet/cheatsheet.html<CR>
" Start python on F5
autocmd FileType python map <F5> :w<CR>:!python "%"<CR>

"autocmd VimEnter * <Plug>CMiniBufExplorer
"autocmd VimEnter * NERDTree

"autocmd MiniBufExplorer VimEnter       * call <SID>DEBUG('-=> VimEnter AutoCmd', 10) |let g:miniBufExplorerAutoUpdate = 1 |call <SID>AutoUpdate(-1,bufnr("%"))

let g:session_autoload = 'no'
let g:session_autosave = 'no'

" no auto load - it destroys the saved session; use \b to load it
let g:miniBufExplorerNoAutoLoad = 1

" move in windows using C-w h/j/k/l
let g:miniBufExplMapWindowNavVim = 1

" move in windows using C-w left / down / up / right
"let g:miniBufExplMapWindowNavArrows = 0

" C-Tab / C-S-Tab
let g:miniBufExplMapCTabSwitchBufs = 1

" for other explorers like TagList
"let g:miniBufExplModSelTarget = 1
