format = """
$time\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
${custom.prompt_symbol}"""

[time]
disabled = false
time_format = "%Y-%m-%d_%H:%M:%S"
format = '[$time]($style) '
style = "bold yellow"

[username]
show_always = true
format = '[$user]($style)'
style_user = "bold green"
style_root = "bold red"

[hostname]
ssh_only = false
format = '[@$hostname]($style) '
style = "bold cyan"

[directory]
truncation_length = 8
truncate_to_repo = false
format = '[$path]($style) '
style = "bold blue"
read_only = " "
read_only_style = "red"

[character]
disabled = true

[custom.prompt_symbol]
command = 'printf "%s" "$STARSHIP_PROMPT_SYMBOL"'
when = 'test -n "$STARSHIP_PROMPT_SYMBOL"'
format = '[$output]($style) '
style = 'bold green'
