(defun my/trigger-bug-554 (arg)
  (interactive "P")
  (evil-collection-init)
  (magit-status)
  (magit-section-toggle (magit-current-section))
  (magit-next-line)
  (magit-show-commit (magit-branch-or-commit-at-point))
  (end-of-buffer)
  (evil-mode)
  (evil-previous-visual-line 2)
  (evil-visual-block)
  (evil-end-of-line)
  (magit-copy-section-value arg)
  )

(defalias 'g 'my/trigger-bug-554)
