#!/bin/bash -e

alias reload='echo "reloading $HOME/.bashrc"; source $HOME/.bashrc'
alias r='reload'

alias clean-workspace='METADA_CORE=.metadata/.plugins/org.eclipse.jdt.core; rm -rf .metadata/.plugins/org.eclipse.core.resources/.history; rm $METADA_CORE/*.index $METADA_CORE/savedIndexNames.txt'
alias unexport='unset'
alias e='echo'
alias envp='env | grep ^PATH='

alias v='vim'

alias cls='clear'
# under linux you may try to use pgreg
alias prep='ps -ef | grep '
alias png='ping -c 5 www.google.com'
alias c='cat'
alias less='less -r'
#alias rm='rm -i'
alias whence='type -a'
#alias ls='ls --color=auto'
alias dir='ls --color=auto --format=vertical'
#alias dir='dir --color=auto'
alias vdir='ls --color=auto --format=long'
#alias vdir='vdir --color=auto'

alias ..='cd ..'
alias ...='cd ../..'
alias cdd='cd -'

# use full command and options names - no gitconfig aliases
git_add_all="echo 'git add .'; git add ."
alias gdd=$git_add_all
alias gal=$git_add_all
alias gg='git gui &'
alias gtg='git tag'
alias gtag='git tag'
alias gbr='git branch'
alias gb='git branch'
alias grbs='git rebase'
alias gr='git rebase'
#alias gdf='git diff'
#alias gp='git push'
alias gpl='git pull'
alias gp='git pull'
alias gh='git push'
# Visualise git log (like gitk, in the terminal)
alias lg='git log --graph --full-history --all --color --pretty=format:"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s"'
alias lg='git log --graph --full-history --all --color --pretty=format:"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s"'

# Compact, colorized git log
alias gl="git log --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"

# Search for a string in all revisions of entire git history
gitSearchStr () {
    git rev-list --all | (
        while read revision; do
            #git grep -F 'Your search string' $revision
            git grep -F '$1' $revision
        done
    )
}
alias gstr=gitSearchStr

ltree () {
    tree -C $* | less -R
}

findreplace () {
    printf "Search: ${1}\n"
    printf "Replace: ${2}\n"
    printf "In: ${3}\n\n"
 
    find . -name "*${3}" -type f | xargs perl -pi -e 's/${1}/${2}/g'
}

extract () {
    if [ -f $1 ] ; then
      case $1 in
        *.tar.bz2)   tar xjf $1     ;;
        *.tar.gz)    tar xzf $1     ;;
        *.bz2)       bunzip2 $1     ;;
        *.rar)       unrar e $1     ;;
        *.gz)        gunzip $1      ;;
        *.tar)       tar xf $1      ;;
        *.tbz2)      tar xjf $1     ;;
        *.tgz)       tar xzf $1     ;;
        *.zip)       unzip $1       ;;
        *.Z)         uncompress $1  ;;
        *.7z)        7z x $1        ;;
        *)     echo "'$1' cannot be extracted via extract()" ;;
         esac
     else
         echo "'$1' is not a valid file"
     fi
}

findTextInAnyFile () {
    echo find . -name "$2" -exec grep -il "$1" {} \;
         find . -name "$2" -exec grep -il "$1" {} \;
}
alias ft=findTextInAnyFile

# create a directory and change into it
function mkdirAndCd() {
  mkdir -p "$1" && cd "$1";
}
alias mcd=mkdirAndCd
alias take=mkdirAndCd

function GitPushRepo {
    echo 'cd '$1' && git push'
    cd $1 && git push
}

function GitPullRepo {
    echo 'cd '$1' && git pull'
    cd $1 && git pull
}

alias ga='_cd=`pwd`; GitPullRepo $dev/cheatsheet && GitPullRepo $dev/dotfiles && cd $_cd'
alias gah='_cd=`pwd`; GitPushRepo $dev/cheatsheet && GitPushRepo $dev/dotfiles && cd $_cd'
#gpl_dotfiles='echo "$dev/dotfiles"; cd $dev/dotfiles && git pull'
#alias gps='cd $dotfilesHOME/vim-pathogen && git submodule foreach git pull origin master'
alias gcl='git clone'
alias gau='git add --update'
alias gss='git status --short'
alias gst='git status'
alias gs='git status'
alias gco='git checkout'
alias gci='git commit'
#alias gdm='git diff master'
#alias gd='git diff | mate'
#alias gnp='git-notpushed'
#alias grm='git status | grep deleted | awk '

alias sc='script/console'
alias h='history'
alias hrep='history | grep '

#alias tu='top -o cpu'
#alias tm='top -o vsize'
#alias r='rake'
#alias mkdir='nocorrect mkdir'
#alias cp='nocorrect cp'
alias md='mkdir -p'
#alias mv='nocorrect mv'
#alias e='exit'
#alias where='command -v'
#alias ff='open -a Firefox'
#alias o='open . &'
#alias less='less -R'

#alias cp='cp -i'
#alias mv='mv -i'

# example:
# alias cvs-reset='cvs update -C -l -d -P "mbsgui/src/de/alldata/mbsgui/base/plugins/CreditKeyList.java" "mbsgui/src/de/alldata/mbsgui/base/plugins/CreditKeyList.java"'
alias cvs-reset='cvs update -C -l -d -P '
alias less='less -r'
alias whence='type -a'
alias dir='ls --color=auto --format=vertical'
alias vdir='ls --color=auto --format=long'

alias l="ls -lAh --color"    # -A does not print the . and .. entries
alias ll="ls -lA --color"
# show hidden files
alias l.='ls -d .* --color=auto'
#alias ls='ls -F --color=tty'
#alias l='ls -lAh'
#alias ls='ls -G'
#alias ls='ls -F --color=tty'
#alias ll='ls -lh'
#alias ll='ls -l'
#alias l='ls -CF'
#alias la='ls -A'
findFile () {
    echo find . -name "$1"
         find . -name "$1"
}
alias f=findFile
alias cx='chmod +x'

#alias cp='cp -i'
#alias mv='mv -i'
#alias grep='grep --color'

if [ "$isCygwin_dev1" -gt 0 ]; then
    :
    #echo "### isCygwin_dev1: $isCygwin_dev1 ==> Loading $strCygwin_dev1 aliases"

    alias clojure='java -cp $winapp/clojure-1.4.0/clojure-1.4.0.jar clojure.main'
elif [ "$isCygwin_155" -gt 0 ]; then
    :
    #echo "### isCygwin_155: $isCygwin_155 ==> Loading $strCygwin_155"

    alias nailgunsrv='ng-server.sh'      # it launches nailgunsrv as a background task
    alias nailguncli='$dev/vimclojure-nailgun-client/ng.exe'
    alias ng='nailguncli'
    alias g='gvim'
    cljcp=`cygpath -w $dev`
    cljcp=$cljcp\;`cygpath -w $dev/clojure/clojure-1.5.1.jar`
    cljcp=$cljcp\;`cygpath -w $dev/clojure-contrib/math.combinatorics-0.0.3.jar`
    cljcp=$cljcp\;`cygpath -w $dev/clojure-contrib/algo.monads-0.1.4.jar`
    cljcp=$cljcp\;`cygpath -w $dev/clojure-contrib/tools.macro-0.1.1.jar`
    cljcp=$cljcp\;`cygpath -w $dev/vimclojure-server/server-2.3.6.jar`
    alias clojure='java -cp $cljcp clojure.main'
    #alias clojure='java -cp `cygpath -w $dev/clojure-1.5.1/clojure-1.5.1.jar` clojure.main'
elif [ "$isMinGw32_155" -gt 0 ]; then
    :
    #echo "### isMinGw32_155: $isMinGw32_155 ==> Loading $strMinGw32_155"

    alias g='gvim -u $HOME/dev/dotfiles/vimrc'
    #alias clojure='$winapp/clojure-1.4.0/clojure.sh'
elif [ "$isCygwin_347" -gt 0 ]; then
    :
    #echo "### isCygwin_347: $isCygwin_347 ==> Loading $strCygwin_347 aliases"

    alias clojure='$winapp/clojure-1.4.0/clojure.sh'
elif [ "$isMinGw32_dev1" -gt 0 ]; then
    :
    #echo "### isMinGw32_dev1: $isMinGw32_dev1 ==> Loading $strMinGw32_dev1 aliases"

    alias clojure='java -cp $winapp/clojure-1.4.0/clojure-1.4.0.jar clojure.main'
elif [ "$isMinGw32_app1" -gt 0 ]; then
    :
    #echo "### isMinGw32_app1: $isMinGw32_app1 ==> Loading $strMinGw32_app1 aliases"

    alias clojure='java -cp $winapp/clojure-1.4.0/clojure-1.4.0.jar clojure.main'
elif [ "$isMinGw32_347" -gt 0 ]; then
    :
    #echo "### isMinGw32_347: $isMinGw32_347 ==> Loading $strMinGw32_347 aliases"

    #alias clojure='$winapp/clojure-1.4.0/clojure.sh'
elif [ "$isLinux" -gt 0 ]; then
    :
    if [ "$isLinux_64" -gt 0 ]; then
        export VMAIL_BROWSER='google-chrome'
    else
        export VMAIL_BROWSER='chromium-browser'
    fi

    export VMAIL_VIM=gvim

    alias lock="xflock4"
    alias u="sudo apt-get update && sudo apt-get upgrade && sudo apt-get clean"
    alias d='sudo apt-get dist-upgrade'
    alias k9='kill -9'
    # I guess '2> /dev/null' redirects errors to /dev/null
    #alias f='find ./ 2> /dev/null'

    # -y  Assume Yes to all queries and do not prompt
    alias inst="sudo apt-get install -y"
    alias uninst="sudo apt-get remove -y"
    alias arem="sudo apt-get autoremove -y"

    alias susp='sudo pm-suspend'
    alias suspend='sudo pm-suspend'
    alias shut='sudo shutdown -h now'
    alias shutdown='sudo shutdown -h now'

    #Search the package list for a regex pattern
    #TODO alias sea='apt-cache search'

    # clojure classpath
    if [ -f $dev/clojure/clojure-1.5.1.jar ]; then
        cljcp=$dev:$dev/clojure/clojure-1.5.1.jar
    else
        echo "Setting aliases: Consider update to clojure-1.5.1.jar"
        cljcp=$dev:$dev/clojure-1.4.0/clojure-1.4.0.jar
    fi
    cljcp=$cljcp:$dev/clojure-contrib/math.combinatorics-0.0.3.jar
    cljcp=$cljcp:$dev/clojure-contrib/algo.monads-0.1.4.jar
    cljcp=$cljcp:$dev/clojure-contrib/tools.macro-0.1.1.jar
    cljcp=$cljcp:$dev/vimclojure-server/server-2.3.6.jar
    alias clojure='java -cp $cljcp clojure.main'
    # stop nailgunsrv: ng ng-stop
    alias nailgunsrv='ng-server.sh'      # it launches nailgunsrv as a background task
    alias nailguncli='ng'
    #alias nailgunsrv='java -cp $cljcp vimclojure.nailgun.NGServer &'
    #alias nailgunsrv='java -cp $cljcp vimclojure.nailgun.NGServer 127.0.0.1 &'
    alias kk="krusader --left . --right . &"
    alias g='gvim -c "call Maximize_Window()"'
    #alias g='gvim -c "call Maximize_Window()" --remote-silent'
    #alias g='gvim'
#else
    #echo "ERROR No environment detected"
fi

if [ "$isLinux" -eq 0 ]; then
    :
    #echo "### isLinux: $isLinux ==> Loading non-linux aliases"

    alias c:='cd $base/c'
    alias d:='cd $base/d'
    alias q:='cd $qDrive'

    alias rosv='cd $rosv'
    #alias conf='cd $rosv/mbs/conf'
    alias deployments='cd $deployments_mce'
    #alias scl='cd $dev/scl-directory'

    alias dem='cd $dev/mbs/dem'
    alias mce='cd $dev/mbs/mce'
    alias std='cd $dev/mbs/std'
    #alias bmw='cd $dev/mbs/bmw'
    #alias mbb='cd $dev/mbs/mbb'

    alias credit='cd $dev/credit'
    alias full='cd $dev/jacarta.full'
    alias light='cd $dev/jacarta.light'
    alias hre='cd $dev/jacarta.hre'
    #alias pfandbrief='cd $dev/pfandbrief'

    #alias services='cd $dev/xml-services'
    #alias xml='cd $dev/xml-services'

    #alias prod='echo ssh rsvoboda@172.17.31.184; ssh rsvoboda@172.17.31.184'
    #alias abnt='echo ssh rsvoboda@172.17.31.185; ssh rsvoboda@172.17.31.185'
    alias prod='echo ssh rsvoboda@194.99.105.205; ssh rsvoboda@194.99.105.205'
    alias abnt='echo ssh rsvoboda@194.99.105.206; ssh rsvoboda@194.99.105.206'

    alias mbssum='$deployments_base/mbssum.sh'

    alias depl='mkdir -p $deployments_full/lib && mkdir -p $deployments_full/deploy; ls -la $deployments_full/..'

#else
#    echo "Linux aliases already loaded"
fi



# this is a rather speculative $home location :)
alias home='cd $dev/..'
alias webcli='cd $dev/webcli'
alias cheatsheet='cd $dev/cheatsheet'
alias dotfiles='cd $dev/dotfiles'
alias trackle='cd $dev/trackle'
alias zark='cd $dev/zark'
alias foo='cd $dev/foo'
alias dev='cd $dev'

# Show which commands you use the most
alias freq='cut -f1 -d" " ~/.bash_history | sort | uniq -c | sort -nr | head -n 30'

# Clear terminal and empty scrollback
alias wipe='printf "\ec"'

alias sulast='sudo $(history -p !-1)'
#alias refunction='$EDITOR ~/.bash_functions && source ~/.bash_functions'
