#!/bin/bash -e
# -e stop on error; -x debug

# shell specific options and information for prompt, shell settings

# change the .history file mode to append
shopt -s histappend

# run at each shell prompt; -a: write immediately the current/new lines to the history file
PROMPT_COMMAND="history -a;$PROMPT_COMMAND"

if [ "$isLinuxNew64" -gt 0 ]; then
    #readFile $bash_files/prompt
    #readFile $bash_files/prompt-sexy

    # TODO add submodule https://github.com/magicmonty/bash-git-prompt.git

    # Set config variables first
    GIT_PROMPT_ONLY_IN_REPO=1

    # as last entry source the gitprompt script
    readFile $dev/bash-git-prompt/gitprompt.sh

elif [ "$isLinux" -gt 0 ]; then
    readFile $bash_files/prompt
    #readFile $bash_files/prompt-sexy
fi
