#!/bin/bash -e
# -e stop on error; -x debug

# operations on directory structure, link-setup etc.

# TODO create a hashmap with machines; store renaming results for a given machine in an own directory
if [ "$isLinuxNew64" -eq 0 ] && [ "$isLinuxFranzi" -eq 0 ] && [ "$isLinuxVB" -eq 0 ]; then
    if [ ! -L $HOME/downloads ]; then
	ln -s $HOME/Downloads $HOME/downloads
    fi

    echo "$HOME/downloads created"
    echo "Prevent this block from re-running on this machine."
    echo isLinux: $isLinux
    echo isLinux_64: $isLinux_64
    echo isLinuxNew64: $isLinuxNew64
    echo isLinuxFranzi: $isLinuxFranzi
    echo isLinuxMartin: $isLinuxMartin
    echo isLinuxMartinJV: $isLinuxMartinJV
    echo isLinuxBambi: $isLinuxBambi
    echo isLinuxVB: $isLinuxVB
fi

if [ "$isLinuxFranzi" -eq 0 ] && [ "$isLinuxMartinJV" -eq 0 ] && [ "$isLinuxNew64" -eq 0 ] && [ "$isLinuxVB" -eq 0 ]; then
    dnameOld=$HOME/dev/dotfiles/vim
    dnameNew=$HOME/dev/dotfiles/.vim
    if [ ! -d "$dnameNew" ]; then
        echo mv $dnameOld $dnameNew
             mv $dnameOld $dnameNew
        echo rm $HOME/.vim
             rm $HOME/.vim
        echo ln -s $HOME/dev/dotfiles/.vim $HOME/.vim
             ln -s $HOME/dev/dotfiles/.vim $HOME/.vim
    else
        echo "WARN: $dnameOld renamed to $dnameNew already."
    fi

    fnameOld=$HOME/dev/dotfiles/vimrc
    fnameNew=$HOME/dev/dotfiles/.vimrc
    if [ ! -f "$dnameNew" ]; then
        echo mv $fnameOld $fnameNew
             mv $fnameOld $fnameNew
        echo rm $HOME/.vimrc
             rm $HOME/.vimrc
        echo ln -s $HOME/dev/dotfiles/.vimrc $HOME/.vimrc
             ln -s $HOME/dev/dotfiles/.vimrc $HOME/.vimrc
    else
        echo "WARN: $fnameOld renamed to $fnameNew already."
    fi

    fnameOld=$HOME/dev/dotfiles/bashrc
    fnameNew=$HOME/dev/dotfiles/.bashrc
    if [ ! -f "$dnameNew" ]; then
        echo mv $fnameOld $fnameNew
             mv $fnameOld $fnameNew
        echo rm $HOME/.bashrc
             rm $HOME/.bashrc
        echo ln -s $HOME/dev/dotfiles/.bashrc $HOME/.bashrc
             ln -s $HOME/dev/dotfiles/.bashrc $HOME/.bashrc
    else
        echo "WARN: $fnameOld renamed to $fnameNew already."
    fi

    if [ -f "$fnameNew" ] && [ -d "$dnameNew" ]; then
        echo "rc-files renamed"
        echo "Prevent this block from re-running on this machine."
        echo isLinux: $isLinux
        echo isLinux_64: $isLinux_64
        echo isLinuxNew64: $isLinuxNew64
        echo isLinuxFranzi: $isLinuxFranzi
        echo isLinuxMartin: $isLinuxMartin
        echo isLinuxMartinJV: $isLinuxMartinJV
        echo isLinuxBambi: $isLinuxBambi
	echo isLinuxVB: $isLinuxVB
    fi
fi
