abiword						install
abiword-common					install
abiword-plugin-grammar				install
abiword-plugin-mathview				install
account-plugin-aim				install
account-plugin-facebook				install
account-plugin-flickr				install
account-plugin-google				install
account-plugin-icons				install
account-plugin-identica				install
account-plugin-jabber				install
account-plugin-salut				install
account-plugin-twitter				install
account-plugin-windows-live			install
account-plugin-yahoo				install
accountsservice					install
ack-grep					install
acl						install
acpi-support					install
acpid						install
activity-log-manager				install
activity-log-manager-control-center		install
adduser						install
adium-theme-ubuntu				install
aisleriot					install
akonadi-backend-mysql				install
akonadi-server					install
alacarte					install
alien						install
alsa-base					install
alsa-utils					install
anacron						install
ant						install
ant-optional					install
antlr3						install
apg						install
app-install-data				install
app-install-data-partner			install
apparmor					install
apparmor-easyprof				install
appmenu-qt					install
appmenu-qt5					install
apport						install
apport-gtk					install
apport-symptoms					install
apt						install
apt-offline					install
apt-transport-https				install
apt-utils					install
apt-xapian-index				install
aptdaemon					install
aptdaemon-data					install
aptitude					install
aptitude-common					install
apturl						install
apturl-common					install
aspectj						install
aspell						install
aspell-en					install
at						install
at-spi2-core					install
autoconf					install
autogen						install
automake					install
autotools-dev					install
avahi-autoipd					install
avahi-daemon					install
avahi-utils					install
bamfdaemon					install
baobab						install
base-files					install
base-passwd					install
bash						install
bash-completion					install
bbswitch-dkms					install
bc						install
bind9-host					install
binutils					install
bison						install
blueman						install
bluez						install
bluez-alsa:amd64				install
bluez-cups					install
bluez-gstreamer					install
branding-ubuntu					install
brasero						install
brasero-cdrkit					install
brasero-common					install
brltty						install
brltty-x11					install
bsdmainutils					install
bsdutils					install
bsh						install
build-essential					install
busybox-initramfs				install
busybox-static					install
bzip2						install
ca-certificates					install
ca-certificates-java				install
cabal-install					install
catfish						install
cdrdao						install
checkbox					install
checkbox-gui					install
checkbox-ng					install
checkbox-ng-service				install
checkbox-qt					install
cheese						install
cheese-common					install
chromium-browser				install
chromium-browser-l10n				install
chromium-codecs-ffmpeg-extra			install
cmatrix						install
cmatrix-xfont					install
colord						install
command-not-found				install
command-not-found-data				install
compiz						install
compiz-core					install
compiz-gnome					install
compiz-plugins-default				install
console-setup					install
consolekit					install
coreutils					install
cpio						install
cpp						install
cpp-4.6						install
cpp-4.7						install
cpp-4.8						install
cracklib-runtime				install
crda						install
cron						install
cryptsetup-bin					install
cups						install
cups-browsed					install
cups-bsd					install
cups-client					install
cups-common					install
cups-core-drivers				install
cups-daemon					install
cups-filters					install
cups-filters-core-drivers			install
cups-pk-helper					install
cups-ppdc					install
cups-server-common				install
curl						install
cvs						install
dash						install
dbus						install
dbus-x11					install
dc						install
dconf-cli					install
dconf-editor					install
dconf-gsettings-backend:amd64			install
dconf-service					install
dconf-tools					install
debconf						install
debconf-i18n					install
debhelper					install
debianutils					install
debugedit					install
deja-dup					install
deja-dup-backend-gvfs				install
desktop-base					install
desktop-file-utils				install
dh-apparmor					install
dh-python					install
dialog						install
dictionaries-common				install
diffstat					install
diffutils					install
dkms						install
dmidecode					install
dmsetup						install
dmz-cursor-theme				install
dnsmasq-base					install
dnsutils					install
doc-base					install
docbook-dsssl					install
docbook-utils					install
docbook-xml					install
docbook-xsl					install
dosfstools					install
dpkg						install
dpkg-dev					install
dstat						install
duplicity					install
dvd+rw-tools					install
e2fslibs:amd64					install
e2fsprogs					install
ed						install
eject						install
ekiga						install
emacs24						install
emacs24-bin-common				install
emacs24-common					install
emacs24-common-non-dfsg				install
emacsen-common					install
empathy						install
empathy-common					install
enchant						install
eog						install
esound-common					install
espeak						install
espeak-data:amd64				install
ethtool						install
evince						install
evince-common					install
evolution-data-server				install
evolution-data-server-common			install
evolution-data-server-online-accounts		install
example-content					install
exo-utils					install
exuberant-ctags					install
fakeroot					install
fdupes						install
file						install
file-roller					install
findutils					install
firefox						install
firefox-globalmenu				install
firefox-locale-de				install
firefox-locale-en				install
flashplugin-installer				install
flex						install
folks-common					install
fontconfig					install
fontconfig-config				install
fonts-dejavu					install
fonts-dejavu-core				install
fonts-dejavu-extra				install
fonts-droid					install
fonts-freefont-ttf				install
fonts-horai-umefont				install
fonts-kacst					install
fonts-kacst-one					install
fonts-khmeros-core				install
fonts-lao					install
fonts-liberation				install
fonts-lklug-sinhala				install
fonts-lyx					install
fonts-mathjax					install
fonts-nanum					install
fonts-opensymbol				install
fonts-sil-abyssinica				install
fonts-sil-padauk				install
fonts-takao-pgothic				install
fonts-thai-tlwg					install
fonts-tibetan-machine				install
fonts-tlwg-garuda				install
fonts-tlwg-kinnari				install
fonts-tlwg-loma					install
fonts-tlwg-mono					install
fonts-tlwg-norasi				install
fonts-tlwg-purisa				install
fonts-tlwg-sawasdee				install
fonts-tlwg-typewriter				install
fonts-tlwg-typist				install
fonts-tlwg-typo					install
fonts-tlwg-umpush				install
fonts-tlwg-waree				install
fonts-unfonts-core				install
fonts-unfonts-extra				install
fonts-wqy-microhei				install
fonts-wqy-zenhei				install
foomatic-db-compressed-ppds			install
foomatic-db-engine				install
fop						install
freepats					install
freerdp-x11					install
friendly-recovery				install
friends						install
friends-dispatcher				install
friends-facebook				install
friends-identica				install
friends-twitter					install
ftp						install
fuse						install
g++						install
g++-4.8						install
gcalctool					install
gcc						install
gcc-4.6						install
gcc-4.6-base:amd64				install
gcc-4.7						install
gcc-4.7-base:amd64				install
gcc-4.8						install
gcc-4.8-base:amd64				install
gcc-4.8-base:i386				install
gcc-4.9-base:amd64				install
gcc-4.9-base:i386				install
gconf-service					install
gconf-service-backend				install
gconf2						install
gconf2-common					install
gcr						install
gdb						install
gdebi						install
gdebi-core					install
gdisk						install
gedit						install
gedit-common					install
genisoimage					install
geoclue						install
geoclue-ubuntu-geoip				install
geoip-database					install
gettext						install
gettext-base					install
ghc						install
ghostscript					install
ghostscript-x					install
gigolo						install
gimp						install
gimp-data					install
gir1.2-accounts-1.0				install
gir1.2-appindicator3-0.1			install
gir1.2-atk-1.0					install
gir1.2-atspi-2.0				install
gir1.2-dbusmenu-glib-0.4			install
gir1.2-dee-1.0					install
gir1.2-ebook-1.2				install
gir1.2-ebookcontacts-1.2			install
gir1.2-edataserver-1.2				install
gir1.2-freedesktop				install
gir1.2-gconf-2.0				install
gir1.2-gdata-0.0				install
gir1.2-gdkpixbuf-2.0				install
gir1.2-glib-2.0					install
gir1.2-gmenu-3.0				install
gir1.2-gnomebluetooth-1.0			install
gir1.2-gnomekeyring-1.0				install
gir1.2-goa-1.0					install
gir1.2-gst-plugins-base-0.10			install
gir1.2-gst-plugins-base-1.0			install
gir1.2-gstreamer-0.10				install
gir1.2-gstreamer-1.0				install
gir1.2-gtk-2.0					install
gir1.2-gtk-3.0					install
gir1.2-gtksource-3.0				install
gir1.2-gudev-1.0				install
gir1.2-ibus-1.0					install
gir1.2-indicate-0.7				install
gir1.2-javascriptcoregtk-3.0			install
gir1.2-messagingmenu-1.0			install
gir1.2-networkmanager-1.0			install
gir1.2-notify-0.7				install
gir1.2-packagekitglib-1.0			install
gir1.2-pango-1.0				install
gir1.2-peas-1.0					install
gir1.2-rb-3.0					install
gir1.2-rsvg-2.0					install
gir1.2-secret-1					install
gir1.2-signon-1.0				install
gir1.2-soup-2.4					install
gir1.2-totem-1.0				install
gir1.2-totem-plparser-1.0			install
gir1.2-udisks-2.0				install
gir1.2-unity-5.0:amd64				install
gir1.2-vte-2.90					install
gir1.2-webkit-3.0				install
gir1.2-wnck-3.0					install
git						install
git-gui						install
git-man						install
gitk						install
gkbd-capplet					install
gksu						install
glib-networking:amd64				install
glib-networking-common				install
glib-networking-services			install
gmusicbrowser					install
gnome-accessibility-themes			install
gnome-bluetooth					install
gnome-calculator				install
gnome-contacts					install
gnome-control-center				install
gnome-control-center-data			install
gnome-control-center-shared-data		install
gnome-desktop-data				install
gnome-desktop3-data				install
gnome-disk-utility				install
gnome-font-viewer				install
gnome-icon-theme				install
gnome-icon-theme-full				install
gnome-icon-theme-symbolic			install
gnome-keyring					install
gnome-mahjongg					install
gnome-media					install
gnome-menus					install
gnome-mines					install
gnome-online-accounts				install
gnome-orca					install
gnome-power-manager				install
gnome-screensaver				install
gnome-screenshot				install
gnome-session					install
gnome-session-bin				install
gnome-session-canberra				install
gnome-session-common				install
gnome-settings-daemon				install
gnome-settings-daemon-schemas			install
gnome-sudoku					install
gnome-system-log				install
gnome-system-monitor				install
gnome-system-tools				install
gnome-terminal					install
gnome-terminal-data				install
gnome-themes-standard:amd64			install
gnome-themes-standard-data			install
gnome-time-admin				install
gnome-user-guide				install
gnome-user-share				install
gnome-video-effects				install
gnomine						install
gnumeric					install
gnumeric-common					install
gnumeric-doc					install
gnupg						install
google-chrome-stable				install
google-talkplugin				install
gparted						install
gpgv						install
gpsbabel					install
gpsbabel-doc					install
graphviz					install
grep						install
groff-base					install
growisofs					install
grub-common					install
grub-gfxpayload-lists				install
grub-pc						install
grub-pc-bin					install
grub2-common					install
gsettings-desktop-schemas			install
gsettings-ubuntu-schemas			install
gsfonts						install
gsfonts-x11					install
gstreamer0.10-alsa:amd64			install
gstreamer0.10-fluendo-mp3:amd64			install
gstreamer0.10-gconf:amd64			install
gstreamer0.10-gnomevfs:amd64			install
gstreamer0.10-nice:amd64			install
gstreamer0.10-plugins-bad:amd64			install
gstreamer0.10-plugins-bad-multiverse		install
gstreamer0.10-plugins-base:amd64		install
gstreamer0.10-plugins-base-apps			install
gstreamer0.10-plugins-good:amd64		install
gstreamer0.10-plugins-ugly:amd64		install
gstreamer0.10-pulseaudio:amd64			install
gstreamer0.10-tools				install
gstreamer0.10-x:amd64				install
gstreamer1.0-alsa:amd64				install
gstreamer1.0-clutter				install
gstreamer1.0-fluendo-mp3:amd64			install
gstreamer1.0-libav:amd64			install
gstreamer1.0-nice:amd64				install
gstreamer1.0-plugins-bad:amd64			install
gstreamer1.0-plugins-bad-faad:amd64		install
gstreamer1.0-plugins-bad-videoparsers:amd64	install
gstreamer1.0-plugins-base:amd64			install
gstreamer1.0-plugins-base-apps			install
gstreamer1.0-plugins-good:amd64			install
gstreamer1.0-plugins-ugly:amd64			install
gstreamer1.0-pulseaudio:amd64			install
gstreamer1.0-tools				install
gstreamer1.0-x:amd64				install
gthumb						install
gthumb-data					install
gtk-theme-config				install
gtk2-engines:amd64				install
gtk2-engines-murrine:amd64			install
gtk2-engines-pixbuf:amd64			install
gtk2-engines-xfce				install
gtk3-engines-unico:amd64			install
guake						install
gucharmap					install
guile-1.8-libs					install
guile-2.0-libs					install
guvcview					install
gv						install
gvfs:amd64					install
gvfs:i386					install
gvfs-backends					install
gvfs-bin					install
gvfs-common					install
gvfs-daemons					install
gvfs-fuse					install
gvfs-libs:amd64					install
gvfs-libs:i386					install
gwibber-service					install
gwibber-service-facebook			install
gwibber-service-identica			install
gwibber-service-twitter				install
gyp						install
gzip						install
hardening-includes				install
hddtemp						install
hdparm						install
heirloom-mailx					install
hicolor-icon-theme				install
hostname					install
hplip						install
hplip-data					install
htop						install
hud						install
humanity-icon-theme				install
hunspell-de-at					install
hunspell-de-ch					install
hunspell-de-de					install
hunspell-en-us					install
hwdata						install
hyphen-de					install
hyphen-en-us					install
ibus						install
ibus-gtk:amd64					install
ibus-gtk3:amd64					install
ibus-pinyin					install
ibus-table					install
icedtea-6-jre-cacao:amd64			install
icedtea-6-jre-jamvm:amd64			install
icedtea-7-jre-jamvm:amd64			install
icedtea-netx:amd64				install
icedtea-netx-common				install
icoutils					install
iftop						install
ifupdown					install
im-config					install
imagemagick-common				install
indicator-applet				install
indicator-applet-appmenu			install
indicator-applet-complete			install
indicator-applet-session			install
indicator-application				install
indicator-application-gtk2			install
indicator-appmenu				install
indicator-bluetooth				install
indicator-datetime				install
indicator-keyboard				install
indicator-messages				install
indicator-power					install
indicator-printers				install
indicator-session				install
indicator-sound					install
indicator-sound-gtk2				install
info						install
init-system-helpers				install
initramfs-tools					install
initramfs-tools-bin				install
initscripts					install
inputattach					install
insserv						install
install-info					install
intel-gpu-tools					install
intltool-debian					install
iproute						install
iproute2					install
iptables					install
iptraf						install
iputils-arping					install
iputils-ping					install
iputils-tracepath				install
irqbalance					install
isc-dhcp-client					install
isc-dhcp-common					install
iso-codes					install
iw						install
jack-tools					install
jackd						install
jackd2						install
jackd2-firewire					install
jadetex						install
java-common					install
java-wrappers					install
javahelp2					install
javascript-common				install
junit						install
junit4						install
kate-data					install
katepart					install
kbd						install
kde-runtime					install
kde-runtime-data				install
kdelibs-bin					install
kdelibs5-data					install
kdelibs5-plugins				install
kdepim-runtime					install
kdepimlibs-kio-plugins				install
kdoctools					install
kerneloops-daemon				install
keyboard-configuration				install
klibc-utils					install
kmod						install
krb5-locales					install
kubuntu-debug-installer				install
landscape-client-ui-install			install
language-pack-de				install
language-pack-de-base				install
language-pack-en				install
language-pack-en-base				install
language-pack-gnome-de				install
language-pack-gnome-de-base			install
language-pack-gnome-en				install
language-pack-gnome-en-base			install
language-selector-common			install
language-selector-gnome				install
laptop-detect					install
less						install
lib32gcc1					install
lib32nss-mdns					install
lib32z1						install
liba52-0.7.4					install
libaa1:amd64					install
libaacs0:amd64					install
libabiword-3.0:amd64				install
libaccount-plugin-1.0-0				install
libaccount-plugin-generic-oauth			install
libaccount-plugin-google			install
libaccounts-glib0:amd64				install
libaccounts-qt1					install
libaccounts-qt5-1				install
libaccountsservice0:amd64			install
libacl1:amd64					install
libacl1:i386					install
libacl1-dev					install
libaether-java					install
libaio1:amd64					install
libakonadi-calendar4				install
libakonadi-contact4				install
libakonadi-kabc4				install
libakonadi-kcal4				install
libakonadi-kde4					install
libakonadi-kmime4				install
libakonadi-notes4				install
libakonadi-socialutils4				install
libakonadiprotocolinternals1			install
libalgorithm-diff-perl				install
libalgorithm-diff-xs-perl			install
libalgorithm-merge-perl				install
libamd2.3.1:amd64				install
libantlr-java					install
libao-common					install
libao4:amd64					install
libaopalliance-java				install
libapache-pom-java				install
libapparmor-perl				install
libapparmor1:amd64				install
libappindicator1				install
libappindicator3-1				install
libapr1:amd64					install
libaprutil1:amd64				install
libapt-inst1.5:amd64				install
libapt-pkg-perl					install
libapt-pkg4.12:amd64				install
libarchive-extract-perl				install
libarchive-zip-perl				install
libarchive13:amd64				install
libart-2.0-2:amd64				install
libart-2.0-dev					install
libasan0:amd64					install
libasm3-java					install
libasn1-8-heimdal:amd64				install
libasound2:amd64				install
libasound2:i386					install
libasound2-data					install
libasound2-dev:amd64				install
libasound2-plugins:amd64			install
libasound2-plugins:i386				install
libaspectj-java					install
libaspell15					install
libasprintf-dev:amd64				install
libasprintf0c2:amd64				install
libass4:amd64					install
libassuan0:amd64				install
libasync-http-client-java			install
libasyncns0:amd64				install
libasyncns0:i386				install
libatasmart4:amd64				install
libatinject-jsr330-api-java			install
libatk-adaptor:amd64				install
libatk-adaptor-data				install
libatk-bridge2.0-0:amd64			install
libatk-bridge2.0-dev:amd64			install
libatk-wrapper-java				install
libatk-wrapper-java-jni:amd64			install
libatk1.0-0:amd64				install
libatk1.0-0:i386				install
libatk1.0-data					install
libatk1.0-dev					install
libatkmm-1.6-1:amd64				install
libatm1:amd64					install
libatomic1:amd64				install
libatspi2.0-0:amd64				install
libattica0.4:amd64				install
libattr1:amd64					install
libattr1:i386					install
libattr1-dev:amd64				install
libaudio2:amd64					install
libaudio2:i386					install
libaudiofile1:amd64				install
libaudit-common					install
libaudit1:amd64					install
libauthen-sasl-perl				install
libautodie-perl					install
libav-tools					install
libavahi-client-dev				install
libavahi-client3:amd64				install
libavahi-client3:i386				install
libavahi-common-data:amd64			install
libavahi-common-data:i386			install
libavahi-common-dev				install
libavahi-common3:amd64				install
libavahi-common3:i386				install
libavahi-core7:amd64				install
libavahi-glib-dev				install
libavahi-glib1:amd64				install
libavahi-gobject0:amd64				install
libavalon-framework-java			install
libavc1394-0:amd64				install
libavcodec54:amd64				install
libavdevice53:amd64				install
libavfilter3:amd64				install
libavformat54:amd64				install
libavresample1:amd64				install
libavutil52:amd64				install
libbabl-0.1-0:amd64				install
libbaloocore4					install
libbaloofiles4					install
libbalooxapian4					install
libbamf3-2:amd64				install
libbasicusageenvironment0			install
libbatik-java					install
libbind9-90					install
libbison-dev:amd64				install
libblas3					install
libblkid1:amd64					install
libbluetooth3:amd64				install
libbluray1:amd64				install
libbonobo2-0:amd64				install
libbonobo2-common				install
libbonobo2-dev:amd64				install
libbonoboui2-0:amd64				install
libbonoboui2-common				install
libbonoboui2-dev:amd64				install
libboost-date-time1.54.0:amd64			install
libboost-filesystem1.54.0:amd64			install
libboost-iostreams1.54.0:amd64			install
libboost-program-options1.54.0:amd64		install
libboost-regex1.54.0:amd64			install
libboost-signals1.54.0:amd64			install
libboost-system1.54.0:amd64			install
libboost-thread1.54.0:amd64			install
libbrasero-media3-1				install
libbrlapi0.6:amd64				install
libbs2b0					install
libbsd-dev					install
libbsd0:amd64					install
libbsf-java					install
libbsh-java					install
libburn4					install
libbz2-1.0:amd64				install
libbz2-1.0:i386					install
libc-ares-dev:amd64				install
libc-ares2:amd64				install
libc-bin					install
libc-dev-bin					install
libc6:amd64					install
libc6:i386					install
libc6-dbg:amd64					install
libc6-dev:amd64					install
libc6-i386					install
libcaca0:amd64					install
libcairo-gobject2:amd64				install
libcairo-perl					install
libcairo-script-interpreter2:amd64		install
libcairo2:amd64					install
libcairo2:i386					install
libcairo2-dev					install
libcairomm-1.0-1:amd64				install
libcamd2.3.1:amd64				install
libcamel-1.2-45					install
libcanberra-dev:amd64				install
libcanberra-gtk-module:amd64			install
libcanberra-gtk0:amd64				install
libcanberra-gtk3-0:amd64			install
libcanberra-gtk3-module:amd64			install
libcanberra-pulse:amd64				install
libcanberra0:amd64				install
libcap-ng0					install
libcap2:amd64					install
libcap2:i386					install
libcap2-bin					install
libcapi20-3:amd64				install
libccolamd2.8.0:amd64				install
libcdaudio1					install
libcddb2					install
libcdi-api-java					install
libcdio-cdda1					install
libcdio-paranoia1				install
libcdio13					install
libcdparanoia0:amd64				install
libcdr-0.0-0					install
libcdt5						install
libcglib-java					install
libcgmanager0:amd64				install
libcgmanager0:i386				install
libcgraph6					install
libchamplain-0.12-0:amd64			install
libchamplain-gtk-0.12-0:amd64			install
libcheese-gtk23:amd64				install
libcheese7:amd64				install
libcholmod2.1.2:amd64				install
libchromaprint0:amd64				install
libck-connector0:amd64				install
libclass-accessor-perl				install
libclass-isa-perl				install
libclassworlds-java				install
libclone-perl					install
libcloog-isl4:amd64				install
libcloog-ppl1:amd64				install
libclucene-contribs1:amd64			install
libclucene-core1:amd64				install
libclutter-1.0-0:amd64				install
libclutter-1.0-common				install
libclutter-gst-1.0-0:amd64			install
libclutter-gst-2.0-0:amd64			install
libclutter-gtk-1.0-0:amd64			install
libcmis-0.4-4					install
libcogl-common					install
libcogl-pango15:amd64				install
libcogl15:amd64					install
libcolamd2.8.0:amd64				install
libcolord1:amd64				install
libcolorhug1:amd64				install
libcolumbus1:amd64				install
libcolumbus1-common				install
libcomerr2:amd64				install
libcomerr2:i386					install
libcommons-beanutils-java			install
libcommons-cli-java				install
libcommons-codec-java				install
libcommons-collections3-java			install
libcommons-configuration-java			install
libcommons-digester-java			install
libcommons-httpclient-java			install
libcommons-io-java				install
libcommons-jexl2-java				install
libcommons-jxpath-java				install
libcommons-lang-java				install
libcommons-logging-java				install
libcommons-net2-java				install
libcommons-parent-java				install
libcommons-vfs-java				install
libcompizconfig0				install
libconfig++9:amd64				install
libcrack2:amd64					install
libcroco3:amd64					install
libcrypt-passwdmd5-perl				install
libcryptsetup4					install
libcrystalhd3:amd64				install
libcuda1-331-updates				install
libcups2:amd64					install
libcups2:i386					install
libcupscgi1:amd64				install
libcupsfilters1:amd64				install
libcupsimage2:amd64				install
libcupsmime1:amd64				install
libcupsppdc1:amd64				install
libcurl3:amd64					install
libcurl3-gnutls:amd64				install
libcurl3-nss:amd64				install
libcwidget3					install
libcwiid1					install
libdaemon0					install
libdatrie-dev:amd64				install
libdatrie1:amd64				install
libdatrie1:i386					install
libdb5.1:amd64					install
libdb5.3:amd64					install
libdbus-1-3:amd64				install
libdbus-1-3:i386				install
libdbus-1-dev:amd64				install
libdbus-glib-1-2:amd64				install
libdbus-glib-1-2:i386				install
libdbusmenu-glib4:amd64				install
libdbusmenu-gtk3-4:amd64			install
libdbusmenu-gtk4:amd64				install
libdbusmenu-qt2:amd64				install
libdbusmenu-qt5:amd64				install
libdc1394-22:amd64				install
libdca0:amd64					install
libdconf1:amd64					install
libdebconfclient0:amd64				install
libdecoration0					install
libdee-1.0-4:amd64				install
libdevmapper-event1.02.1:amd64			install
libdevmapper1.02.1:amd64			install
libdigest-crc-perl				install
libdigest-hmac-perl				install
libdirac-encoder0:amd64				install
libdirectfb-1.2-9:amd64				install
libdiscid0:amd64				install
libdjvulibre-text				install
libdjvulibre21:amd64				install
libdlrestrictions1				install
libdmapsharing-3.0-2				install
libdmtx0a:amd64					install
libdns100					install
libdom4j-java					install
libdotconf0:amd64				install
libdoxia-java					install
libdpkg-perl					install
libdrm-dev:amd64				install
libdrm-intel1:amd64				install
libdrm-intel1:i386				install
libdrm-nouveau2:amd64				install
libdrm-nouveau2:i386				install
libdrm-radeon1:amd64				install
libdrm-radeon1:i386				install
libdrm2:amd64					install
libdrm2:i386					install
libdv4:amd64					install
libdvbpsi8:amd64				install
libdvdnav4:amd64				install
libdvdread4:amd64				install
libeasymock-java				install
libebackend-1.2-7				install
libebml4:amd64					install
libebook-1.2-14					install
libebook-contacts-1.2-0				install
libecal-1.2-16					install
libedata-book-1.2-20				install
libedata-cal-1.2-23				install
libedataserver-1.2-18				install
libedit2:amd64					install
libegl1-mesa:amd64				install
libegl1-mesa-drivers:amd64			install
libelf1:amd64					install
libelf1:i386					install
libelfg0:amd64					install
libemail-valid-perl				install
libenca0:amd64					install
libenchant1c2a:amd64				install
libencode-locale-perl				install
libept1.4.12:amd64				install
libepub0					install
liberror-perl					install
libesd0:amd64					install
libespeak1:amd64				install
libestr0					install
libevdocument3-4				install
libevent-2.0-5:amd64				install
libevview3-3					install
libexcalibur-logkit-java			install
libexempi3:amd64				install
libexif12:amd64					install
libexiv2-12					install
libexo-1-0:amd64				install
libexo-common					install
libexo-helpers					install
libexpat1:amd64					install
libexpat1:i386					install
libexpat1-dev:amd64				install
libexttextcat-2.0-0				install
libexttextcat-data				install
libfaac0:amd64					install
libfaad2:amd64					install
libfakeroot:amd64				install
libfarstream-0.1-0:amd64			install
libfarstream-0.2-2:amd64			install
libfelix-framework-java				install
libfelix-main-java				install
libffado2					install
libffi-dev:amd64				install
libffi6:amd64					install
libffi6:i386					install
libfftw3-3:amd64				install
libfftw3-double3:amd64				install
libfftw3-long3:amd64				install
libfftw3-single3:amd64				install
libfile-basedir-perl				install
libfile-copy-recursive-perl			install
libfile-desktopentry-perl			install
libfile-fcntllock-perl				install
libfile-listing-perl				install
libfile-mimeinfo-perl				install
libfile-next-perl				install
libfl-dev:amd64					install
libflac8:amd64					install
libflac8:i386					install
libflite1:amd64					install
libfluidsynth1:amd64				install
libfolks-eds25:amd64				install
libfolks-telepathy25:amd64			install
libfolks25:amd64				install
libfont-afm-perl				install
libfontconfig1:amd64				install
libfontconfig1:i386				install
libfontconfig1-dev				install
libfontembed1:amd64				install
libfontenc1:amd64				install
libfop-java					install
libframe6:amd64					install
libfreerdp-plugins-standard:amd64		install
libfreerdp1:amd64				install
libfreetype6:amd64				install
libfreetype6:i386				install
libfreetype6-dev				install
libfribidi0:amd64				install
libfriends0:amd64				install
libfs6:amd64					install
libfuse2:amd64					install
libgail-3-0:amd64				install
libgail-common:amd64				install
libgail-dev					install
libgail18:amd64					install
libganymed-ssh2-java				install
libgarcon-1-0					install
libgarcon-common				install
libgbm1:amd64					install
libgc1c2:amd64					install
libgcc-4.7-dev:amd64				install
libgcc-4.8-dev:amd64				install
libgcc1:amd64					install
libgcc1:i386					install
libgck-1-0:amd64				install
libgconf-2-4:amd64				install
libgconf-2-4:i386				install
libgconf2-4:amd64				install
libgconf2-4:i386				install
libgconf2-dev					install
libgcr-3-1:amd64				install
libgcr-3-common					install
libgcr-base-3-1:amd64				install
libgcr-ui-3-1:amd64				install
libgcrypt11:amd64				install
libgcrypt11:i386				install
libgcrypt11-dev					install
libgd3:amd64					install
libgdata-common					install
libgdata13					install
libgdbm3:amd64					install
libgdk-pixbuf2.0-0:amd64			install
libgdk-pixbuf2.0-0:i386				install
libgdk-pixbuf2.0-common				install
libgdk-pixbuf2.0-dev				install
libgdome2-0					install
libgdome2-cpp-smart0c2a				install
libgee-0.8-2:amd64				install
libgee2:amd64					install
libgegl-0.2-0:amd64				install
libgeis1:amd64					install
libgeoclue0:amd64				install
libgeoip1:amd64					install
libgeronimo-interceptor-3.0-spec-java		install
libgeronimo-jpa-2.0-spec-java			install
libgeronimo-osgi-support-java			install
libgettextpo-dev:amd64				install
libgettextpo0:amd64				install
libgexiv2-2:amd64				install
libgfortran3:amd64				install
libgif-dev					install
libgif4:amd64					install
libgimp2.0					install
libgirepository-1.0-1				install
libgksu2-0					install
libgl1-mesa-dev					install
libgl1-mesa-dri:amd64				install
libgl1-mesa-dri:i386				install
libgl1-mesa-glx:amd64				install
libgl1-mesa-glx:i386				install
libglade2-0:amd64				install
libglamor0:amd64				install
libglapi-mesa:amd64				install
libglapi-mesa:i386				install
libgles2-mesa:amd64				install
libglew1.10:amd64				install
libglewmx1.10:amd64				install
libglib-perl					install
libglib2.0-0:amd64				install
libglib2.0-0:i386				install
libglib2.0-bin					install
libglib2.0-data					install
libglib2.0-dev					install
libglibmm-2.4-1c2a:amd64			install
libglu1-mesa:amd64				install
libglu1-mesa:i386				install
libglu1-mesa-dev				install
libgme0						install
libgmime-2.6-0:amd64				install
libgmp-dev:amd64				install
libgmp10:amd64					install
libgmpxx4ldbl:amd64				install
libgnome-bluetooth11				install
libgnome-control-center1			install
libgnome-desktop-3-7				install
libgnome-keyring-common				install
libgnome-keyring-dev				install
libgnome-keyring0:amd64				install
libgnome-media-profiles-3.0-0			install
libgnome-menu-3-0				install
libgnome-menu2					install
libgnome2-0:amd64				install
libgnome2-bin					install
libgnome2-common				install
libgnome2-dev:amd64				install
libgnomecanvas2-0:amd64				install
libgnomecanvas2-common				install
libgnomecanvas2-dev:amd64			install
libgnomekbd-common				install
libgnomekbd8					install
libgnomeui-0:amd64				install
libgnomeui-common				install
libgnomeui-dev:amd64				install
libgnomevfs2-0:amd64				install
libgnomevfs2-common				install
libgnomevfs2-dev:amd64				install
libgnomevfs2-extra:amd64			install
libgnutls-dev					install
libgnutls-openssl27:amd64			install
libgnutls26:amd64				install
libgnutls26:i386				install
libgnutls28:amd64				install
libgnutlsxx27:amd64				install
libgoa-1.0-0b:amd64				install
libgoa-1.0-common				install
libgoa-backend-1.0-1:amd64			install
libgoffice-0.10-10				install
libgoffice-0.10-10-common			install
libgomp1:amd64					install
libgpg-error-dev				install
libgpg-error0:amd64				install
libgpg-error0:i386				install
libgpgme11:amd64				install
libgphoto2-6:amd64				install
libgphoto2-l10n					install
libgphoto2-port10:amd64				install
libgpm-dev:amd64				install
libgpm2:amd64					install
libgpm2:i386					install
libgpod-common					install
libgpod4:amd64					install
libgrail6					install
libgraphite2-3:amd64				install
libgraphite2-3:i386				install
libgraphite3					install
libgrip0					install
libgroupsock1					install
libgs9						install
libgs9-common					install
libgsettings-qt1:amd64				install
libgsf-1-114					install
libgsf-1-common					install
libgsm1:amd64					install
libgsoap4:amd64					install
libgssapi-krb5-2:amd64				install
libgssapi-krb5-2:i386				install
libgssapi3-heimdal:amd64			install
libgssdp-1.0-3					install
libgstreamer-perl				install
libgstreamer-plugins-bad0.10-0:amd64		install
libgstreamer-plugins-bad1.0-0:amd64		install
libgstreamer-plugins-base0.10-0:amd64		install
libgstreamer-plugins-base1.0-0:amd64		install
libgstreamer-plugins-base1.0-0:i386		install
libgstreamer-plugins-good1.0-0:amd64		install
libgstreamer0.10-0:amd64			install
libgstreamer1.0-0:amd64				install
libgstreamer1.0-0:i386				install
libgtk-3-0:amd64				install
libgtk-3-bin					install
libgtk-3-common					install
libgtk-3-dev					install
libgtk2-notify-perl				install
libgtk2-perl					install
libgtk2-trayicon-perl				install
libgtk2.0-0:amd64				install
libgtk2.0-0:i386				install
libgtk2.0-bin					install
libgtk2.0-common				install
libgtk2.0-dev					install
libgtkglext1					install
libgtkmathview0c2a				install
libgtkmm-2.4-1c2a:amd64				install
libgtkmm-3.0-1:amd64				install
libgtksourceview-3.0-1:amd64			install
libgtksourceview-3.0-common			install
libgtksourceview2.0-0				install
libgtksourceview2.0-common			install
libgtkspell0					install
libgtop2-7					install
libgtop2-common					install
libguava-java					install
libgucharmap-2-90-7				install
libgudev-1.0-0:amd64				install
libguice-java					install
libgupnp-1.0-4					install
libgupnp-igd-1.0-4:amd64			install
libgusb2:amd64					install
libgutenprint2					install
libgvc6						install
libgvpr2					install
libgweather-3-6					install
libgweather-common				install
libgxps2:amd64					install
libhamcrest-java				install
libharfbuzz-dev					install
libharfbuzz-gobject0:amd64			install
libharfbuzz-icu0:amd64				install
libharfbuzz0b:amd64				install
libharfbuzz0b:i386				install
libhcrypto4-heimdal:amd64			install
libheimbase1-heimdal:amd64			install
libheimntlm0-heimdal:amd64			install
libhogweed2:amd64				install
libhpmud0					install
libhtml-form-perl				install
libhtml-format-perl				install
libhtml-parser-perl				install
libhtml-tagset-perl				install
libhtml-tree-perl				install
libhttp-cookies-perl				install
libhttp-daemon-perl				install
libhttp-date-perl				install
libhttp-message-perl				install
libhttp-negotiate-perl				install
libhttpclient-java				install
libhttpcore-java				install
libhud-gtk1:amd64				install
libhud-gtk1-dev:amd64				install
libhud2:amd64					install
libhud2-dev:amd64				install
libhunspell-1.3-0:amd64				install
libhx509-5-heimdal:amd64			install
libhyphen0					install
libibus-1.0-5:amd64				install
libical1					install
libice-dev:amd64				install
libice6:amd64					install
libice6:i386					install
libicu52:amd64					install
libid3tag0					install
libidl-common					install
libidl-dev:amd64				install
libidl0:amd64					install
libidn11:amd64					install
libido-0.1-0:amd64				install
libido3-0.1-0:amd64				install
libiec61883-0:amd64				install
libieee1284-3:amd64				install
libijs-0.35					install
libilmbase6:amd64				install
libimobiledevice4:amd64				install
libindicate5					install
libindicator3-7					install
libindicator7					install
libintl-perl					install
libio-html-perl					install
libio-pty-perl					install
libio-socket-inet6-perl				install
libio-socket-ssl-perl				install
libio-string-perl				install
libipc-run-perl					install
libipc-system-simple-perl			install
libisc95					install
libisccc90					install
libisccfg90					install
libisl10:amd64					install
libiso9660-8					install
libisofs6					install
libitext1-java					install
libitm1:amd64					install
libiw30:amd64					install
libjack-jackd2-0:amd64				install
libjack-jackd2-0:i386				install
libjackrabbit-java				install
libjasper1:amd64				install
libjasper1:i386					install
libjavascriptcoregtk-1.0-0:amd64		install
libjavascriptcoregtk-3.0-0:amd64		install
libjaxen-java					install
libjaxp1.3-java					install
libjbig-dev:amd64				install
libjbig0:amd64					install
libjbig0:i386					install
libjbig2dec0					install
libjcommander-java				install
libjdom1-java					install
libjetty-java					install
libjline-java					install
libjna-java					install
libjpeg-dev:amd64				install
libjpeg-turbo8:amd64				install
libjpeg-turbo8:i386				install
libjpeg-turbo8-dev:amd64			install
libjpeg8:amd64					install
libjpeg8:i386					install
libjpeg8-dev:amd64				install
libjs-jquery					install
libjs-mathjax					install
libjs-node-uuid					install
libjsch-java					install
libjson-c2:amd64				install
libjson-c2:i386					install
libjson-glib-1.0-0:amd64			install
libjson-glib-1.0-common				install
libjson0:amd64					install
libjson0:i386					install
libjsoup-java					install
libjsr305-java					install
libjte1						install
libk5crypto3:amd64				install
libk5crypto3:i386				install
libkabc4					install
libkactivities-bin				install
libkactivities-models1				install
libkactivities6					install
libkalarmcal2					install
libkate1					install
libkatepartinterfaces4				install
libkcal4					install
libkcalcore4					install
libkcalutils4					install
libkcmutils4					install
libkde3support4					install
libkdeclarative5				install
libkdecore5					install
libkdesu5					install
libkdeui5					install
libkdewebkit5					install
libkdnssd4					install
libkemoticons4					install
libkexiv2-11					install
libkexiv2-data					install
libkeybinder0					install
libkeyutils1:amd64				install
libkeyutils1:i386				install
libkfbapi1					install
libkfile4					install
libkgapi2-2:amd64				install
libkholidays4					install
libkhtml5					install
libkidletime4					install
libkimap4					install
libkio5						install
libkjsapi4					install
libkjsembed4					install
libkldap4					install
libklibc					install
libkmbox4					install
libkmediaplayer4				install
libkmime4					install
libkmod2:amd64					install
libknewstuff2-4					install
libknewstuff3-4					install
libknotifyconfig4				install
libkntlm4					install
libkolab0					install
libkolabxml1					install
libkparts4					install
libkpathsea6					install
libkpimidentities4				install
libkpimtextedit4				install
libkpimutils4					install
libkprintutils4					install
libkpty4					install
libkrb5-26-heimdal:amd64			install
libkrb5-3:amd64					install
libkrb5-3:i386					install
libkrb5support0:amd64				install
libkrb5support0:i386				install
libkresources4					install
libkrosscore4					install
libkscreen1					install
libktexteditor4					install
libkubuntu0					install
libkxmlrpcclient4				install
liblangtag-common				install
liblangtag1					install
liblapack3					install
liblcms1:amd64					install
liblcms2-2:amd64				install
libldap-2.4-2:amd64				install
libldb1:amd64					install
liblightdm-gobject-1-0				install
liblink-grammar4				install
liblircclient0					install
liblist-moreutils-perl				install
liblivemedia23					install
libllvm3.4:amd64				install
libllvm3.4:i386					install
liblo7						install
liblocale-gettext-perl				install
liblockfile-bin					install
liblockfile1:amd64				install
liblog-message-simple-perl			install
liblog4j1.2-java				install
libloudmouth1-0					install
liblouis-data					install
liblouis2:amd64					install
liblqr-1-0:amd64				install
libltdl7:amd64					install
liblua5.1-0:amd64				install
liblua5.1-0-dev:amd64				install
liblua5.2-0:amd64				install
liblvm2app2.2:amd64				install
liblwp-mediatypes-perl				install
liblwp-protocol-https-perl			install
liblwres90					install
liblzma-dev:amd64				install
liblzma5:amd64					install
liblzma5:i386					install
liblzo2-2:amd64					install
libm17n-0					install
libm17n-dev					install
libmad0:amd64					install
libmagic1:amd64					install
libmagickcore5:amd64				install
libmagickwand5:amd64				install
libmail-sendmail-perl				install
libmailtools-perl				install
libmailtransport4				install
libmatroska6:amd64				install
libmaven-parent-java				install
libmaven-scm-java				install
libmaven2-core-java				install
libmbim-glib0:amd64				install
libmeanwhile1					install
libmessaging-menu0				install
libmetacity-private0a				install
libmhash2:amd64					install
libmicroblog4					install
libmikmod2:amd64				install
libmimic0					install
libminiupnpc8					install
libmission-control-plugins0			install
libmjpegutils-2.1-0				install
libmm-glib0:amd64				install
libmms0:amd64					install
libmng2:amd64					install
libmnl0:amd64					install
libmodello-java					install
libmodplug1					install
libmodule-pluggable-perl			install
libmotif-common					install
libmount1:amd64					install
libmp3lame0:amd64				install
libmpc3:amd64					install
libmpcdec6					install
libmpdec2:amd64					install
libmpeg2-4:amd64				install
libmpeg2encpp-2.1-0				install
libmpfr4:amd64					install
libmpg123-0:amd64				install
libmplex2-2.1-0					install
libmrm4:amd64					install
libmspub-0.0-0					install
libmtdev1:amd64					install
libmtp-common					install
libmtp-runtime					install
libmtp9:amd64					install
libmusicbrainz5-0:amd64				install
libmx-1.0-2:amd64				install
libmx-bin					install
libmx-common					install
libmxml1					install
libmysqlclient18:amd64				install
libmysqlclient18:i386				install
libmythes-1.2-0					install
libnatpmp1					install
libnautilus-extension1a				install
libnb-org-openide-modules-java			install
libnb-org-openide-util-java			install
libnb-org-openide-util-lookup-java		install
libnb-platform13-java				install
libncurses5:amd64				install
libncurses5:i386				install
libncurses5-dev:amd64				install
libncursesw5:amd64				install
libncursesw5:i386				install
libneon27-gnutls				install
libnepomuk4					install
libnepomukcleaner4				install
libnepomukcore4abi1				install
libnepomukquery4a				install
libnepomukutils4				install
libnet-dbus-perl				install
libnet-dns-perl					install
libnet-domain-tld-perl				install
libnet-http-perl				install
libnet-ip-perl					install
libnet-smtp-ssl-perl				install
libnet-ssleay-perl				install
libnetbeans-cvsclient-java			install
libnetfilter-conntrack3:amd64			install
libnettle4:amd64				install
libnetty-java					install
libnewt0.52:amd64				install
libnfnetlink0:amd64				install
libnice10:amd64					install
libnih-dbus1:amd64				install
libnih-dbus1:i386				install
libnih1:amd64					install
libnih1:i386					install
libnl-3-200:amd64				install
libnl-genl-3-200:amd64				install
libnl-route-3-200:amd64				install
libnm-glib-vpn1					install
libnm-glib4					install
libnm-gtk-common				install
libnm-gtk0					install
libnm-util2					install
libnotify-bin					install
libnotify4:amd64				install
libnspr4:amd64					install
libnspr4:i386					install
libnspr4-0d:amd64				install
libnspr4-0d:i386				install
libnss-mdns:amd64				install
libnss-mdns:i386				install
libnss-mdns-i386				install
libnss3:amd64					install
libnss3:i386					install
libnss3-1d:amd64				install
libnss3-1d:i386					install
libnss3-nssdb					install
libntdb1:amd64					install
libntrack-qt4-1					install
libntrack0					install
libnuma1:amd64					install
libnux-4.0-0					install
libnux-4.0-common				install
liboauth0:amd64					install
libodbc1:amd64					install
libofa0						install
libogg0:amd64					install
libogg0:i386					install
liboil0.3:amd64					install
libokularcore4					install
liboobs-1-5					install
libopal3.10.10					install
libopenal-data					install
libopenal1:amd64				install
libopencc1:amd64				install
libopencore-amrnb0:amd64			install
libopencore-amrwb0:amd64			install
libopencv-calib3d2.4:amd64			install
libopencv-contrib2.4:amd64			install
libopencv-core2.4:amd64				install
libopencv-features2d2.4:amd64			install
libopencv-flann2.4:amd64			install
libopencv-highgui2.4:amd64			install
libopencv-imgproc2.4:amd64			install
libopencv-legacy2.4:amd64			install
libopencv-ml2.4:amd64				install
libopencv-objdetect2.4:amd64			install
libopencv-video2.4:amd64			install
libopenexr6:amd64				install
libopenjpeg2:amd64				install
libopenobex1					install
libopenvg1-mesa:amd64				install
libopts25:amd64					install
libopts25-dev					install
libopus0					install
liborbit-2-0:amd64				install
liborbit2:amd64					install
liborbit2-dev					install
liborc-0.4-0:amd64				install
liborc-0.4-0:i386				install
liborcus-0.6-0					install
liboro-java					install
libosgi-compendium-java				install
libosgi-core-java				install
libosgi-foundation-ee-java			install
libosp5						install
libostyle1c2					install
libotf-dev:amd64				install
libotf0:amd64					install
libotr5						install
libots0						install
liboxideqt-qmlplugin:amd64			install
liboxideqtcore0:amd64				install
libp11-kit-dev					install
libp11-kit-gnome-keyring:amd64			install
libp11-kit0:amd64				install
libp11-kit0:i386				install
libpackagekit-glib2-16:amd64			install
libpam-cap:amd64				install
libpam-ck-connector:amd64			install
libpam-freerdp					install
libpam-gnome-keyring:amd64			install
libpam-modules:amd64				install
libpam-modules-bin				install
libpam-runtime					install
libpam-systemd:amd64				install
libpam0g:amd64					install
libpanel-applet-4-0				install
libpango-1.0-0:amd64				install
libpango-1.0-0:i386				install
libpango-perl					install
libpango1.0-0:amd64				install
libpango1.0-dev					install
libpangocairo-1.0-0:amd64			install
libpangocairo-1.0-0:i386			install
libpangoft2-1.0-0:amd64				install
libpangoft2-1.0-0:i386				install
libpangomm-1.4-1:amd64				install
libpangox-1.0-0:amd64				install
libpangoxft-1.0-0:amd64				install
libpaper-utils					install
libpaper1:amd64					install
libparse-debianchangelog-perl			install
libparted0debian1:amd64				install
libpathplan4					install
libpcap0.8:amd64				install
libpci3:amd64					install
libpciaccess0:amd64				install
libpciaccess0:i386				install
libpcre3:amd64					install
libpcre3:i386					install
libpcre3-dev:amd64				install
libpcrecpp0:amd64				install
libpcsclite1:amd64				install
libpeas-1.0-0					install
libpeas-common					install
libperl-dev					install
libperl4-corelibs-perl				install
libperl5.18					install
libperlio-gzip-perl				install
libphonon4:amd64				install
libpipeline1:amd64				install
libpixman-1-0:amd64				install
libpixman-1-0:i386				install
libpixman-1-dev					install
libplasma3					install
libplexus-ant-factory-java			install
libplexus-archiver-java				install
libplexus-bsh-factory-java			install
libplexus-build-api-java			install
libplexus-cipher-java				install
libplexus-classworlds-java			install
libplexus-classworlds2-java			install
libplexus-cli-java				install
libplexus-container-default-java		install
libplexus-containers-java			install
libplexus-containers1.5-java			install
libplexus-i18n-java				install
libplexus-interactivity-api-java		install
libplexus-interpolation-java			install
libplexus-io-java				install
libplexus-sec-dispatcher-java			install
libplexus-utils-java				install
libplexus-utils2-java				install
libplist1:amd64					install
libplymouth2:amd64				install
libpng12-0:amd64				install
libpng12-0:i386					install
libpng12-dev					install
libpocketsphinx1				install
libpod-latex-perl				install
libpolkit-agent-1-0:amd64			install
libpolkit-backend-1-0:amd64			install
libpolkit-gobject-1-0:amd64			install
libpolkit-qt-1-1				install
libpoppler-glib8:amd64				install
libpoppler-qt4-4:amd64				install
libpoppler44:amd64				install
libpopt-dev:amd64				install
libpopt0:amd64					install
libportaudio2:amd64				install
libpostproc52					install
libppl-c4:amd64					install
libppl13:amd64					install
libprison0:amd64				install
libprocps3:amd64				install
libprotobuf8:amd64				install
libprotoc8:amd64				install
libproxy-tools					install
libproxy1:amd64					install
libproxy1-plugin-gsettings:amd64		install
libproxy1-plugin-networkmanager:amd64		install
libpt2.10.10					install
libptexenc1					install
libpth20:amd64					install
libpthread-stubs0-dev:amd64			install
libpulse-mainloop-glib0:amd64			install
libpulse0:amd64					install
libpulse0:i386					install
libpulsedsp:amd64				install
libpurple-bin					install
libpurple0					install
libpwquality-common				install
libpwquality1:amd64				install
libpython-dev:amd64				install
libpython-stdlib:amd64				install
libpython2.7:amd64				install
libpython2.7-dev:amd64				install
libpython2.7-minimal:amd64			install
libpython2.7-stdlib:amd64			install
libpython3-stdlib:amd64				install
libpython3.4:amd64				install
libpython3.4-minimal:amd64			install
libpython3.4-stdlib:amd64			install
libpyzy-1.0-0					install
libqapt2					install
libqapt2-runtime				install
libqca2:amd64					install
libqdox-java					install
libqimageblitz4					install
libqjson0:amd64					install
libqmi-glib0:amd64				install
libqmobipocket1					install
libqpdf13:amd64					install
libqrencode3:amd64				install
libqt4-dbus:amd64				install
libqt4-dbus:i386				install
libqt4-declarative:amd64			install
libqt4-declarative:i386				install
libqt4-designer:amd64				install
libqt4-dev					install
libqt4-dev-bin					install
libqt4-help:amd64				install
libqt4-network:amd64				install
libqt4-network:i386				install
libqt4-opengl:amd64				install
libqt4-opengl:i386				install
libqt4-opengl-dev				install
libqt4-qt3support:amd64				install
libqt4-script:amd64				install
libqt4-script:i386				install
libqt4-scripttools:amd64			install
libqt4-sql:amd64				install
libqt4-sql:i386					install
libqt4-sql-mysql:amd64				install
libqt4-sql-mysql:i386				install
libqt4-sql-sqlite:amd64				install
libqt4-svg:amd64				install
libqt4-test:amd64				install
libqt4-xml:amd64				install
libqt4-xml:i386					install
libqt4-xmlpatterns:amd64			install
libqt4-xmlpatterns:i386				install
libqt5core5a:amd64				install
libqt5dbus5:amd64				install
libqt5feedback5:amd64				install
libqt5gui5:amd64				install
libqt5multimedia5:amd64				install
libqt5network5:amd64				install
libqt5opengl5:amd64				install
libqt5organizer5:amd64				install
libqt5positioning5:amd64			install
libqt5printsupport5:amd64			install
libqt5qml-graphicaleffects:amd64		install
libqt5qml5:amd64				install
libqt5quick5:amd64				install
libqt5sensors5:amd64				install
libqt5sql5:amd64				install
libqt5sql5-sqlite:amd64				install
libqt5svg5:amd64				install
libqt5test5:amd64				install
libqt5webkit5:amd64				install
libqt5webkit5-qmlwebkitplugin:amd64		install
libqt5widgets5:amd64				install
libqt5xml5:amd64				install
libqtassistantclient4:amd64			install
libqtcore4:amd64				install
libqtcore4:i386					install
libqtdbus4:amd64				install
libqtdbus4:i386					install
libqtgui4:amd64					install
libqtgui4:i386					install
libqtwebkit-dev					install
libqtwebkit4:amd64				install
libqtwebkit4:i386				install
libquadmath0:amd64				install
libquvi-scripts					install
libquvi7:amd64					install
libraptor2-0:amd64				install
librarian0					install
librasqal3:amd64				install
libraw1394-11:amd64				install
libraw9:amd64					install
librdf0:amd64					install
libreadline-dev:amd64				install
libreadline5:amd64				install
libreadline6:amd64				install
libreadline6-dev:amd64				install
libregexp-java					install
libreoffice-avmedia-backend-gstreamer		install
libreoffice-base-core				install
libreoffice-calc				install
libreoffice-common				install
libreoffice-core				install
libreoffice-draw				install
libreoffice-emailmerge				install
libreoffice-gnome				install
libreoffice-gtk					install
libreoffice-help-de				install
libreoffice-help-en-us				install
libreoffice-impress				install
libreoffice-l10n-de				install
libreoffice-math				install
libreoffice-ogltrans				install
libreoffice-pdfimport				install
libreoffice-presentation-minimizer		install
libreoffice-presenter-console			install
libreoffice-style-human				install
libreoffice-style-tango				install
libreoffice-writer				install
libresid-builder0c2a				install
librest-0.7-0:amd64				install
librhino-java					install
librhythmbox-core8				install
libroken18-heimdal:amd64			install
librpm3						install
librpmbuild3					install
librpmio3					install
librpmsign1					install
librsvg2-2:amd64				install
librsvg2-common:amd64				install
librsvg2-dev					install
librsync1:amd64					install
librtmp0:amd64					install
libruby1.9.1					install
libsamplerate0:amd64				install
libsamplerate0:i386				install
libsane:amd64					install
libsane-common					install
libsane-hpaio					install
libsasl2-2:amd64				install
libsasl2-modules:amd64				install
libsasl2-modules-db:amd64			install
libsaxon-java					install
libsbc1:amd64					install
libschroedinger-1.0-0:amd64			install
libscsynth1					install
libsdl-image1.2:amd64				install
libsdl-mixer1.2:amd64				install
libsdl-ttf2.0-0:amd64				install
libsdl1.2debian:amd64				install
libsecret-1-0:amd64				install
libsecret-1-0:i386				install
libsecret-common				install
libselinux1:amd64				install
libselinux1:i386				install
libselinux1-dev:amd64				install
libsemanage-common				install
libsemanage1:amd64				install
libsensors4:amd64				install
libsepol1:amd64					install
libsepol1-dev					install
libserf-1-1:amd64				install
libservlet2.5-java				install
libservlet3.0-java				install
libsexy2					install
libsgmls-perl					install
libsgutils2-2					install
libshout3:amd64					install
libsidplay1					install
libsidplay2					install
libsigc++-2.0-0c2a:amd64			install
libsignon-extension1				install
libsignon-glib1					install
libsignon-plugins-common1			install
libsignon-qt1					install
libsignon-qt5-1					install
libsigsegv2:amd64				install
libsisu-guice-java				install
libsisu-ioc-java				install
libslang2:amd64					install
libslang2:i386					install
libslf4j-java					install
libslv2-9					install
libsm-dev:amd64					install
libsm6:amd64					install
libsm6:i386					install
libsmbclient:amd64				install
libsndfile1:amd64				install
libsndfile1:i386				install
libsnmp-base					install
libsnmp30:amd64					install
libsocket6-perl					install
libsofia-sip-ua-glib3				install
libsofia-sip-ua0				install
libsolid4					install
libsonic0:amd64					install
libsoprano4					install
libsoundtouch0:amd64				install
libsoup-gnome2.4-1:amd64			install
libsoup2.4-1:amd64				install
libsp1c2					install
libspandsp2					install
libspectre1:amd64				install
libspeechd2:amd64				install
libspeex1:amd64					install
libspeexdsp1:amd64				install
libspeexdsp1:i386				install
libsphinxbase1					install
libspice-server1:amd64				install
libsqlite3-0:amd64				install
libsqlite3-0:i386				install
libsrtp0					install
libss2:amd64					install
libssh-4:amd64					install
libssh2-1:amd64					install
libssl-dev:amd64				install
libssl-doc					install
libssl1.0.0:amd64				install
libssl1.0.0:i386				install
libstartup-notification0:amd64			install
libstdc++-4.8-dev:amd64				install
libstdc++6:amd64				install
libstdc++6:i386					install
libstdc++6-4.7-dev:amd64			install
libstreamanalyzer0				install
libstreams0					install
libstringtemplate-java				install
libsub-identify-perl				install
libsub-name-perl				install
libsvga1:amd64					install
libsvn1:amd64					install
libswing-layout-java				install
libswitch-perl					install
libswscale2:amd64				install
libsys-hostname-long-perl			install
libsysfs2:amd64					install
libsystemd-daemon0:amd64			install
libsystemd-journal0:amd64			install
libsystemd-login0:amd64				install
libt1-5						install
libtag1-vanilla:amd64				install
libtag1c2a:amd64				install
libtagc0:amd64					install
libtalloc2:amd64				install
libtar0						install
libtasn1-6:amd64				install
libtasn1-6:i386					install
libtasn1-6-dev					install
libtbb2						install
libtcl8.5:amd64					install
libtcl8.6:amd64					install
libtdb1:amd64					install
libtelepathy-farstream2:amd64			install
libtelepathy-farstream3:amd64			install
libtelepathy-glib0:amd64			install
libtelepathy-logger3:amd64			install
libterm-ui-perl					install
libtevent0:amd64				install
libtext-charwidth-perl				install
libtext-iconv-perl				install
libtext-levenshtein-perl			install
libtext-soundex-perl				install
libtext-unidecode-perl				install
libtext-wrapi18n-perl				install
libthai-data					install
libthai-dev:amd64				install
libthai0:amd64					install
libthai0:i386					install
libtheora0:amd64				install
libthreadweaver4				install
libthumbnailer0:amd64				install
libthunarx-2-0					install
libtidy-0.99-0					install
libtie-ixhash-perl				install
libtiff4-dev:amd64				install
libtiff5:amd64					install
libtiff5:i386					install
libtiff5-dev:amd64				install
libtiffxx5:amd64				install
libtimedate-perl				install
libtimezonemap1					install
libtinfo-dev:amd64				install
libtinfo5:amd64					install
libtinfo5:i386					install
libtk8.6:amd64					install
libtotem-plparser18				install
libtotem0					install
libts-0.0-0:amd64				install
libtsan0:amd64					install
libtumbler-1-0					install
libtwolame0					install
libtxc-dxtn-s2tc0:amd64				install
libtxc-dxtn-s2tc0:i386				install
libudev-dev					install
libudev0:amd64					install
libudev1:amd64					install
libudev1:i386					install
libudisks2-0:amd64				install
libufe-xidgetter0				install
libuil4:amd64					install
libumfpack5.6.2:amd64				install
libunique-1.0-0					install
libunistring0:amd64				install
libunity-action-qt1:amd64			install
libunity-control-center1			install
libunity-core-6.0-9				install
libunity-gtk2-parser0:amd64			install
libunity-gtk3-parser0:amd64			install
libunity-misc4					install
libunity-protocol-private0:amd64		install
libunity-scopes-json-def-desktop		install
libunity-webapps0				install
libunity9:amd64					install
libunityvoice1:amd64				install
libupnp6					install
libupower-glib1:amd64				install
libupstart1:amd64				install
liburi-perl					install
liburl-dispatcher1:amd64			install
libusageenvironment1				install
libusb-0.1-4:amd64				install
libusb-1.0-0:amd64				install
libusbmuxd2					install
libustr-1.0-1:amd64				install
libutempter0					install
libuuid-perl					install
libuuid1:amd64					install
libuuid1:i386					install
libv4l-0:amd64					install
libv4lconvert0:amd64				install
libv8-3.14-dev					install
libv8-3.14.5					install
libva-x11-1:amd64				install
libva1:amd64					install
libvcdinfo0					install
libvdpau1:amd64					install
libvirtodbc0					install
libvisio-0.0-0					install
libvisual-0.4-0:amd64				install
libvisual-0.4-0:i386				install
libvisual-0.4-plugins:amd64			install
libvisual-0.4-plugins:i386			install
libvlc5						install
libvlccore7					install
libvncserver0:amd64				install
libvo-aacenc0:amd64				install
libvo-amrwbenc0:amd64				install
libvorbis0a:amd64				install
libvorbis0a:i386				install
libvorbisenc2:amd64				install
libvorbisenc2:i386				install
libvorbisfile3:amd64				install
libvpx1:amd64					install
libvte-2.90-9					install
libvte-2.90-common				install
libvte-common					install
libvte9						install
libwacom-common					install
libwacom2:amd64					install
libwagon-java					install
libwagon2-java					install
libwavpack1:amd64				install
libwayland-client0:amd64			install
libwayland-cursor0:amd64			install
libwayland-dev					install
libwayland-egl1-mesa:amd64			install
libwayland-server0:amd64			install
libwbclient0:amd64				install
libwebcam0					install
libwebkit2gtk-3.0-25:amd64			install
libwebkitgtk-1.0-0:amd64			install
libwebkitgtk-1.0-common				install
libwebkitgtk-3.0-0:amd64			install
libwebkitgtk-3.0-common				install
libwebp5:amd64					install
libwebpmux1:amd64				install
libwhoopsie-preferences0			install
libwhoopsie0					install
libwildmidi-config				install
libwildmidi1:amd64				install
libwind0-heimdal:amd64				install
libwmf0.2-7:amd64				install
libwmf0.2-7-gtk					install
libwnck-3-0:amd64				install
libwnck-3-common				install
libwnck-common					install
libwnck22					install
libwpd-0.9-9					install
libwpg-0.2-2					install
libwps-0.2-2					install
libwrap0:amd64					install
libwrap0:i386					install
libwv-1.2-4:amd64				install
libwww-perl					install
libwww-robotrules-perl				install
libx11-6:amd64					install
libx11-6:i386					install
libx11-data					install
libx11-dev:amd64				install
libx11-doc					install
libx11-xcb-dev:amd64				install
libx11-xcb1:amd64				install
libx11-xcb1:i386				install
libx264-142:amd64				install
libx86-1:amd64					install
libxalan2-java					install
libxapian22					install
libxatracker2:amd64				install
libxau-dev:amd64				install
libxau6:amd64					install
libxau6:i386					install
libxaw7:amd64					install
libxaw7-dev:amd64				install
libxbean-java					install
libxcb-composite0:amd64				install
libxcb-dri2-0:amd64				install
libxcb-dri2-0:i386				install
libxcb-dri2-0-dev:amd64				install
libxcb-dri3-0:amd64				install
libxcb-dri3-0:i386				install
libxcb-dri3-dev:amd64				install
libxcb-glx0:amd64				install
libxcb-glx0:i386				install
libxcb-glx0-dev:amd64				install
libxcb-icccm4:amd64				install
libxcb-image0:amd64				install
libxcb-keysyms1:amd64				install
libxcb-present-dev:amd64			install
libxcb-present0:amd64				install
libxcb-present0:i386				install
libxcb-randr0:amd64				install
libxcb-randr0-dev:amd64				install
libxcb-render-util0:amd64			install
libxcb-render0:amd64				install
libxcb-render0:i386				install
libxcb-render0-dev:amd64			install
libxcb-shape0:amd64				install
libxcb-shape0-dev:amd64				install
libxcb-shm0:amd64				install
libxcb-shm0:i386				install
libxcb-shm0-dev:amd64				install
libxcb-sync-dev:amd64				install
libxcb-sync1:amd64				install
libxcb-sync1:i386				install
libxcb-util0:amd64				install
libxcb-xfixes0:amd64				install
libxcb-xfixes0-dev:amd64			install
libxcb-xkb1:amd64				install
libxcb-xv0:amd64				install
libxcb1:amd64					install
libxcb1:i386					install
libxcb1-dev:amd64				install
libxcomposite-dev				install
libxcomposite1:amd64				install
libxcomposite1:i386				install
libxcursor-dev:amd64				install
libxcursor1:amd64				install
libxcursor1:i386				install
libxdamage-dev:amd64				install
libxdamage1:amd64				install
libxdamage1:i386				install
libxdmcp-dev:amd64				install
libxdmcp6:amd64					install
libxdmcp6:i386					install
libxerces-c3.1:amd64				install
libxerces2-java					install
libxext-dev:amd64				install
libxext6:amd64					install
libxext6:i386					install
libxfce4ui-1-0					install
libxfce4ui-2-0					install
libxfce4ui-common				install
libxfce4ui-utils				install
libxfce4util-bin				install
libxfce4util-common				install
libxfce4util6					install
libxfcegui4-4					install
libxfconf-0-2					install
libxfixes-dev:amd64				install
libxfixes3:amd64				install
libxfixes3:i386					install
libxfont1:amd64					install
libxft-dev					install
libxft2:amd64					install
libxi-dev					install
libxi6:amd64					install
libxi6:i386					install
libxinerama-dev:amd64				install
libxinerama1:amd64				install
libxinerama1:i386				install
libxkbcommon-dev				install
libxkbcommon0:amd64				install
libxkbfile1:amd64				install
libxklavier16					install
libxm4:amd64					install
libxml++2.6-2					install
libxml-commons-external-java			install
libxml-commons-resolver1.1-java			install
libxml-libxml-perl				install
libxml-namespacesupport-perl			install
libxml-parser-perl				install
libxml-sax-base-perl				install
libxml-sax-expat-perl				install
libxml-sax-perl					install
libxml-twig-perl				install
libxml-xpath-perl				install
libxml2:amd64					install
libxml2:i386					install
libxml2-dev:amd64				install
libxml2-utils					install
libxmlgraphics-commons-java			install
libxmu-dev:amd64				install
libxmu-headers					install
libxmu6:amd64					install
libxmuu1:amd64					install
libxom-java					install
libxp6:amd64					install
libxpm-dev:amd64				install
libxpm4:amd64					install
libxpp2-java					install
libxpp3-java					install
libxrandr-dev:amd64				install
libxrandr2:amd64				install
libxrandr2:i386					install
libxrender-dev:amd64				install
libxrender1:amd64				install
libxrender1:i386				install
libxres1:amd64					install
libxshmfence-dev:amd64				install
libxshmfence1:amd64				install
libxshmfence1:i386				install
libxslt1.1:amd64				install
libxslt1.1:i386					install
libxss1:amd64					install
libxss1:i386					install
libxt-dev:amd64					install
libxt6:amd64					install
libxt6:i386					install
libxtables10					install
libxtst6:amd64					install
libxv1:amd64					install
libxv1:i386					install
libxvidcore4:amd64				install
libxvmc1:amd64					install
libxxf86dga1:amd64				install
libxxf86vm-dev:amd64				install
libxxf86vm1:amd64				install
libxxf86vm1:i386				install
libyajl2:amd64					install
libyaml-0-2:amd64				install
libyaml-snake-java				install
libyaml-tiny-perl				install
libyelp0					install
libzbar0					install
libzeitgeist-1.0-1				install
libzeitgeist-2.0-0:amd64			install
libzephyr4:amd64				install
libzip2						install
libzvbi-common					install
libzvbi0:amd64					install
light-locker					install
light-locker-settings				install
light-themes					install
lightdm						install
lightdm-gtk-greeter				install
lightdm-remote-session-freerdp			install
lightdm-remote-session-uccsconfigure		install
link-grammar-dictionaries-en			install
lintian						install
linux-firmware					install
linux-headers-3.13.0-24				install
linux-headers-3.13.0-24-generic			install
linux-headers-generic				install
linux-image-3.11.0-20-generic			install
linux-image-3.13.0-24-generic			install
linux-image-3.5.0-23-generic			install
linux-image-extra-3.11.0-20-generic		install
linux-image-extra-3.13.0-24-generic		install
linux-image-extra-3.5.0-23-generic		install
linux-image-generic				install
linux-libc-dev:amd64				install
linux-sound-base				install
linux-source					install
linux-source-3.13.0				install
lm-sensors					install
locales						install
locate						install
lockfile-progs					install
login						install
logrotate					install
lp-solve					install
lsb-base					install
lsb-core					install
lsb-invalid-mta					install
lsb-release					install
lsb-security					install
lshw						install
lsof						install
ltrace						install
lua5.1						install
luatex						install
lynx						install
lynx-cur					install
m17n-contrib					install
m17n-db						install
m4						install
make						install
makedev						install
man-db						install
manpages					install
manpages-dev					install
maven						install
mawk						install
mcp-account-manager-uoa				install
media-player-info				install
memtest86+					install
menu						install
menulibre					install
mercurial					install
mercurial-common				install
mesa-common-dev					install
mesa-utils					install
metacity-common					install
mime-support					install
mlocate						install
mobile-broadband-provider-info			install
modemmanager					install
module-init-tools				install
mount						install
mountall					install
mousepad					install
mousetweaks					install
mplayer						install
mplayer-gui					install
mplayer-skins					install
mscompress					install
mtools						install
mtp-tools					install
mtpfs						install
mtr-tiny					install
mugshot						install
multiarch-support				install
myspell-en-au					install
myspell-en-gb					install
myspell-en-za					install
mysql-client-core-5.5				install
mysql-common					install
mysql-server-core-5.5				install
mythes-de					install
mythes-de-ch					install
mythes-en-us					install
nano						install
nautilus					install
nautilus-data					install
nautilus-dropbox				install
nautilus-sendto					install
nautilus-sendto-empathy				install
nautilus-share					install
ncurses-base					install
ncurses-bin					install
ncurses-term					install
nepomuk-core					install
nepomuk-core-data				install
nepomuk-core-runtime				install
net-tools					install
netbase						install
netcat-openbsd					install
network-manager					install
network-manager-gnome				install
network-manager-pptp				install
network-manager-pptp-gnome			install
node-abbrev					install
node-ansi					install
node-archy					install
node-async					install
node-block-stream				install
node-combined-stream				install
node-cookie-jar					install
node-delayed-stream				install
node-forever-agent				install
node-form-data					install
node-fstream					install
node-fstream-ignore				install
node-github-url-from-git			install
node-glob					install
node-graceful-fs				install
node-gyp					install
node-inherits					install
node-ini					install
node-json-stringify-safe			install
node-lockfile					install
node-lru-cache					install
node-mime					install
node-minimatch					install
node-mkdirp					install
node-mute-stream				install
node-node-uuid					install
node-nopt					install
node-normalize-package-data			install
node-npmlog					install
node-once					install
node-osenv					install
node-qs						install
node-read					install
node-read-package-json				install
node-request					install
node-retry					install
node-rimraf					install
node-semver					install
node-sha					install
node-sigmund					install
node-slide					install
node-tar					install
node-tunnel-agent				install
node-which					install
nodejs						install
nodejs-dev					install
notify-osd					install
notify-osd-icons				install
npm						install
ntfs-3g						install
ntpdate						install
ntrack-module-libnl-0				install
nux-tools					install
nvidia-319-updates				install
nvidia-331-updates				install
nvidia-libopencl1-331-updates			install
nvidia-opencl-icd-331-updates			install
nvidia-prime					install
nvidia-settings					install
obex-data-server				install
obexd-client					install
odbcinst					install
odbcinst1debian2:amd64				install
okular						install
onboard						install
onboard-data					install
oneconf						install
oneconf-common					install
openjade					install
openjdk-6-jdk:amd64				install
openjdk-6-jre:amd64				install
openjdk-6-jre-headless:amd64			install
openjdk-6-jre-lib				install
openjdk-7-jdk:amd64				install
openjdk-7-jre:amd64				install
openjdk-7-jre-headless:amd64			install
openoffice.org-hyphenation			install
openprinting-ppds				install
openssh-client					install
openssh-server					install
openssh-sftp-server				install
openssl						install
orage						install
orbit2						install
os-prober					install
overlay-scrollbar				install
overlay-scrollbar-gtk2:amd64			install
overlay-scrollbar-gtk3:amd64			install
oxideqt-codecs-extra:amd64			install
oxygen-icon-theme				install
p11-kit						install
p11-kit-modules:amd64				install
parole						install
parted						install
passwd						install
pastebinit					install
patch						install
patchutils					install
pavucontrol					install
pax						install
pciutils					install
pcmciautils					install
perl						install
perl-base					install
perl-modules					install
phonon:amd64					install
phonon-backend-gstreamer:amd64			install
phonon-backend-gstreamer-common:amd64		install
pidgin						install
pidgin-data					install
pidgin-libnotify				install
pidgin-microblog				install
pidgin-otr					install
pidgin-skype					install
pidgin-skype-common				install
pkg-config					install
plainbox-provider-checkbox			install
plainbox-provider-resource-generic		install
plainbox-secure-policy				install
plasma-scriptengine-javascript			install
plymouth					install
plymouth-label					install
plymouth-theme-ubuntu-logo			install
plymouth-theme-ubuntu-text			install
plymouth-theme-xubuntu-logo			install
plymouth-theme-xubuntu-text			install
pm-utils					install
po-debconf					install
policykit-1					install
policykit-1-gnome				install
policykit-desktop-privileges			install
polkit-kde-1					install
poppler-data					install
poppler-utils					install
popularity-contest				install
powermgmt-base					install
powertop					install
ppp						install
pppconfig					install
pppoeconf					install
pptp-linux					install
printer-driver-c2esp				install
printer-driver-foo2zjs				install
printer-driver-foo2zjs-common			install
printer-driver-gutenprint			install
printer-driver-hpcups				install
printer-driver-hpijs				install
printer-driver-min12xxw				install
printer-driver-pnm2ppa				install
printer-driver-postscript-hp			install
printer-driver-ptouch				install
printer-driver-pxljr				install
printer-driver-sag-gdi				install
printer-driver-splix				install
procps						install
protobuf-compiler				install
psmisc						install
pulseaudio					install
pulseaudio-module-bluetooth			install
pulseaudio-module-gconf				install
pulseaudio-module-x11				install
pulseaudio-utils				install
pv						install
python						install
python-appindicator				install
python-apport					install
python-apt					install
python-apt-common				install
python-aptdaemon				install
python-aptdaemon.gtk3widgets			install
python-cairo					install
python-chardet					install
python-commandnotfound				install
python-configglue				install
python-configobj				install
python-crypto					install
python-cups					install
python-cupshelpers				install
python-dateutil					install
python-dbus					install
python-dbus-dev					install
python-debian					install
python-debtagshw				install
python-defer					install
python-dev					install
python-dirspec					install
python-django					install
python-gconf					install
python-gdbm					install
python-gi					install
python-gi-cairo					install
python-glade2					install
python-gnomekeyring				install
python-gnupginterface				install
python-gobject					install
python-gobject-2				install
python-gpgme					install
python-gst0.10					install
python-gtk2					install
python-httplib2					install
python-ibus					install
python-imaging					install
python-kde4					install
python-keyring					install
python-launchpadlib				install
python-lazr.restfulclient			install
python-lazr.uri					install
python-ldb					install
python-libxml2					install
python-lockfile					install
python-lxml					install
python-mako					install
python-markupsafe				install
python-matplotlib				install
python-matplotlib-data				install
python-minimal					install
python-notify					install
python-ntdb					install
python-numpy					install
python-oauth					install
python-oauthlib					install
python-oneconf					install
python-openssl					install
python-pam					install
python-pexpect					install
python-pil					install
python-piston-mini-client			install
python-pkg-resources				install
python-problem-report				install
python-protobuf					install
python-psutil					install
python-pycurl					install
python-pyinotify				install
python-pyparsing				install
python-qt4					install
python-qt4-dbus					install
python-renderpm					install
python-reportlab				install
python-reportlab-accel				install
python-requests					install
python-samba					install
python-secretstorage				install
python-serial					install
python-simplejson				install
python-sip					install
python-six					install
python-smbc					install
python-software-properties			install
python-support					install
python-talloc					install
python-tdb					install
python-tk					install
python-twisted-bin				install
python-twisted-core				install
python-twisted-names				install
python-twisted-web				install
python-tz					install
python-ubuntu-sso-client			install
python-urllib3					install
python-vte					install
python-wadllib					install
python-xapian					install
python-xdg					install
python-zeitgeist				install
python-zope.interface				install
python2.7					install
python2.7-dev					install
python2.7-minimal				install
python3						install
python3-apparmor				install
python3-apport					install
python3-apt					install
python3-aptdaemon				install
python3-aptdaemon.gtk3widgets			install
python3-aptdaemon.pkcompat			install
python3-brlapi					install
python3-cairo					install
python3-chardet					install
python3-checkbox				install
python3-checkbox-ng				install
python3-checkbox-support			install
python3-commandnotfound				install
python3-crypto					install
python3-dbus					install
python3-debian					install
python3-defer					install
python3-distupgrade				install
python3-feedparser				install
python3-gdbm:amd64				install
python3-gi					install
python3-gi-cairo				install
python3-httplib2				install
python3-libapparmor				install
python3-louis					install
python3-lxml					install
python3-mako					install
python3-markupsafe				install
python3-minimal					install
python3-oauthlib				install
python3-oneconf					install
python3-pexpect					install
python3-piston-mini-client			install
python3-pkg-resources				install
python3-plainbox				install
python3-problem-report				install
python3-psutil					install
python3-pyatspi					install
python3-pyatspi2				install
python3-pycurl					install
python3-pyparsing				install
python3-requests				install
python3-six					install
python3-software-properties			install
python3-speechd					install
python3-uno					install
python3-update-manager				install
python3-urllib3					install
python3-virtkey					install
python3-xdg					install
python3-xkit					install
python3.4					install
python3.4-minimal				install
qapt-batch					install
qdbus						install
qjackctl					install
qpdf						install
qt-at-spi:amd64					install
qt4-default					install
qt4-linguist-tools				install
qt4-qmake					install
qtchooser					install
qtcore4-l10n					install
qtdeclarative5-accounts-plugin			install
qtdeclarative5-dialogs-plugin:amd64		install
qtdeclarative5-localstorage-plugin:amd64	install
qtdeclarative5-privatewidgets-plugin:amd64	install
qtdeclarative5-qtfeedback-plugin:amd64		install
qtdeclarative5-qtquick2-plugin:amd64		install
qtdeclarative5-ubuntu-ui-extras-browser-plugin:amd64	install
qtdeclarative5-ubuntu-ui-extras-browser-plugin-assets	install
qtdeclarative5-ubuntu-ui-toolkit-plugin:amd64	install
qtdeclarative5-unity-action-plugin:amd64	install
qtdeclarative5-window-plugin:amd64		install
radeontool					install
rarian-compat					install
readline-common					install
remmina						install
remmina-common					install
remmina-plugin-rdp				install
remmina-plugin-vnc				install
remote-login-service				install
resolvconf					install
rfkill						install
rhino						install
rhythmbox					install
rhythmbox-data					install
rhythmbox-mozilla				install
rhythmbox-plugin-cdrecorder			install
rhythmbox-plugin-magnatune			install
rhythmbox-plugin-zeitgeist			install
rhythmbox-plugins				install
ristretto					install
rpm						install
rpm-common					install
rpm2cpio					install
rsync						install
rsyslog						install
rtkit						install
rtmpdump					install
ruby						install
ruby-dev					install
ruby1.9.1					install
ruby1.9.1-dev					install
samba-common					install
samba-common-bin				install
samba-libs:amd64				install
sane-utils					install
screen-resolution-extra				install
screensaver-default-images			install
seahorse					install
sed						install
sensible-utils					install
session-migration				install
sessioninstaller				install
sgml-base					install
sgml-data					install
sgmlspl						install
shared-desktop-ontologies			install
shared-mime-info				install
shimmer-themes					install
shotwell					install
shotwell-common					install
signon-keyring-extension			install
signon-plugin-oauth2				install
signon-plugin-password				install
signon-ui					install
signond						install
simple-scan					install
skype						install
smbclient					install
sni-qt:amd64					install
software-center					install
software-center-aptdaemon-plugins		install
software-properties-common			install
software-properties-gtk				install
soprano-daemon					install
sound-theme-freedesktop				install
sp						install
speech-dispatcher				install
speech-dispatcher-audio-plugins:amd64		install
sphinx-voxforge-hmm-en				install
sphinx-voxforge-lm-en				install
ssh						install
ssh-askpass-gnome				install
ssh-import-id					install
ssl-cert					install
steam-launcher					install
strace						install
subversion					install
sudo						install
supercollider					install
supercollider-common				install
supercollider-ide				install
supercollider-language				install
supercollider-server				install
supercollider-supernova				install
synaptic					install
syslinux					install
syslinux-common					install
syslinux-legacy					install
system-config-printer-common			install
system-config-printer-gnome			install
system-config-printer-udev			install
system-tools-backends				install
systemd-services				install
systemd-shim					install
sysv-rc						install
sysvinit-utils					install
t1utils						install
tango-icon-theme				install
tar						install
tcl						install
tcl-dev:amd64					install
tcl8.5						install
tcl8.6						install
tcl8.6-dev:amd64				install
tcpd						install
tcpdump						install
telepathy-gabble				install
telepathy-haze					install
telepathy-idle					install
telepathy-indicator				install
telepathy-logger				install
telepathy-mission-control-5			install
telepathy-rakia					install
telepathy-salut					install
telepathy-sofiasip				install
telnet						install
testng						install
tex-common					install
texinfo						install
texlive-base					install
texlive-binaries				install
texlive-fonts-recommended			install
texlive-generic-recommended			install
texlive-latex-base				install
texlive-latex-recommended			install
thin-client-config-agent			install
thunar						install
thunar-archive-plugin				install
thunar-data					install
thunar-media-tags-plugin			install
thunar-volman					install
thunderbird					install
thunderbird-globalmenu				install
thunderbird-gnome-support			install
thunderbird-locale-de				install
thunderbird-locale-en				install
thunderbird-locale-en-us			install
time						install
timidity					install
timidity-daemon					install
tipa						install
tk						install
tk8.6						install
tofrodos					install
toshset						install
totem						install
totem-common					install
totem-mozilla					install
totem-plugins					install
traceroute					install
transmission-common				install
transmission-gtk				install
tree						install
tsconf						install
ttf-dejavu					install
ttf-dejavu-core					install
ttf-dejavu-extra				install
ttf-indic-fonts-core				install
ttf-punjabi-fonts				install
ttf-thai-tlwg					install
ttf-ubuntu-font-family				install
ttf-umefont					install
ttf-unfonts-core				install
ttf-unfonts-extra				install
ttf-wqy-microhei				install
ttf-wqy-zenhei					install
tumbler						install
tumbler-common					install
tzdata						install
tzdata-java					install
ubuntu-artwork					install
ubuntu-desktop					install
ubuntu-docs					install
ubuntu-drivers-common				install
ubuntu-extras-keyring				install
ubuntu-keyring					install
ubuntu-minimal					install
ubuntu-mono					install
ubuntu-release-upgrader-core			install
ubuntu-release-upgrader-gtk			install
ubuntu-restricted-addons			install
ubuntu-restricted-extras			install
ubuntu-session					install
ubuntu-settings					install
ubuntu-sounds					install
ubuntu-sso-client				install
ubuntu-sso-client-qt				install
ubuntu-standard					install
ubuntu-system-service				install
ubuntu-ui-toolkit-theme				install
ubuntu-wallpapers				install
ubuntu-wallpapers-quantal			install
ubuntu-wallpapers-raring			install
ubuntu-wallpapers-saucy				install
ubuntu-wallpapers-trusty			install
ubuntuone-client-data				install
ucf						install
udev						install
udisks						install
udisks2						install
ufoai						install
ufoai-data					install
ufoai-music					install
ufoai-server-data				install
ufw						install
unattended-upgrades				install
unity						install
unity-asset-pool				install
unity-control-center				install
unity-control-center-signon			install
unity-greeter					install
unity-gtk-module-common				install
unity-gtk2-module:amd64				install
unity-gtk3-module:amd64				install
unity-lens-applications				install
unity-lens-files				install
unity-lens-friends				install
unity-lens-gwibber				install
unity-lens-music				install
unity-lens-photos				install
unity-lens-video				install
unity-scope-audacious				install
unity-scope-calculator				install
unity-scope-chromiumbookmarks			install
unity-scope-clementine				install
unity-scope-colourlovers			install
unity-scope-devhelp				install
unity-scope-firefoxbookmarks			install
unity-scope-gdocs				install
unity-scope-gdrive				install
unity-scope-gmusicbrowser			install
unity-scope-gourmet				install
unity-scope-guayadeque				install
unity-scope-home				install
unity-scope-manpages				install
unity-scope-musicstores				install
unity-scope-musique				install
unity-scope-openclipart				install
unity-scope-texdoc				install
unity-scope-tomboy				install
unity-scope-video-remote			install
unity-scope-virtualbox				install
unity-scope-yelp				install
unity-scope-zotero				install
unity-scopes-master-default			install
unity-scopes-runner				install
unity-services					install
unity-settings-daemon				install
unity-voice-service:amd64			install
unity-webapps-common				install
unity-webapps-gmail				install
unity-webapps-googledocs			install
unity-webapps-googleplus			install
unity-webapps-lastfm-radio			install
unity-webapps-launchpad				install
unity-webapps-qml				install
unity-webapps-reddit				install
unity-webapps-service				install
unity-webapps-tumblr				install
unity-webapps-twitter				install
unity-webapps-youtube				install
uno-libs3					install
unrar						install
unzip						install
update-inetd					install
update-manager					install
update-manager-core				install
update-notifier					install
update-notifier-common				install
upower						install
upstart						install
ure						install
ureadahead					install
usb-creator-common				install
usb-creator-gtk					install
usb-modeswitch					install
usb-modeswitch-data				install
usbmuxd						install
usbutils					install
util-linux					install
uuid-runtime					install
uvcdynctrl					install
uvcdynctrl-data					install
vbetool						install
vcdimager					install
vim						install
vim-common					install
vim-dbg						install
vim-gnome					install
vim-gtk						install
vim-gui-common					install
vim-runtime					install
vim-tiny					install
vino						install
virtualbox					install
virtualbox-dkms					install
virtualbox-qt					install
virtuoso-minimal				install
virtuoso-opensource-6.1-bin			install
virtuoso-opensource-6.1-common			install
visualvm					install
vlc						install
vlc-data					install
vlc-nox						install
vlc-plugin-notify				install
vlc-plugin-pulse				install
vrms						install
wamerican					install
warsow						install
warsow-data					install
wbritish					install
webaccounts-extension-common			install
webapp-container				install
webbrowser-app					install
webcam						install
wget						install
whiptail					install
whoopsie					install
whoopsie-preferences				install
wireless-regdb					install
wireless-tools					install
wngerman					install
wodim						install
wogerman					install
wpasupplicant					install
wswiss						install
x11-apps					install
x11-common					install
x11-session-utils				install
x11-utils					install
x11-xfs-utils					install
x11-xkb-utils					install
x11-xserver-utils				install
x11proto-composite-dev				install
x11proto-core-dev				install
x11proto-damage-dev				install
x11proto-dri2-dev				install
x11proto-fixes-dev				install
x11proto-gl-dev					install
x11proto-input-dev				install
x11proto-kb-dev					install
x11proto-randr-dev				install
x11proto-render-dev				install
x11proto-xext-dev				install
x11proto-xf86vidmode-dev			install
x11proto-xinerama-dev				install
xauth						install
xaw3dg:amd64					install
xawtv-plugins					install
xbitmaps					install
xbrlapi						install
xchat						install
xchat-common					install
xchat-indicator					install
xcursor-themes					install
xdg-user-dirs					install
xdg-user-dirs-gtk				install
xdg-utils					install
xdiagnose					install
xfburn						install
xfce-keyboard-shortcuts				install
xfce4						install
xfce4-appfinder					install
xfce4-artwork					install
xfce4-battery-plugin				install
xfce4-clipman					install
xfce4-clipman-plugin				install
xfce4-cpufreq-plugin				install
xfce4-cpugraph-plugin				install
xfce4-datetime-plugin				install
xfce4-dict					install
xfce4-diskperf-plugin				install
xfce4-fsguard-plugin				install
xfce4-genmon-plugin				install
xfce4-goodies					install
xfce4-indicator-plugin				install
xfce4-mailwatch-plugin				install
xfce4-mixer					install
xfce4-mount-plugin				install
xfce4-netload-plugin				install
xfce4-notes					install
xfce4-notes-plugin				install
xfce4-notifyd					install
xfce4-panel					install
xfce4-places-plugin				install
xfce4-power-manager				install
xfce4-power-manager-data			install
xfce4-quicklauncher-plugin			install
xfce4-screenshooter				install
xfce4-sensors-plugin				install
xfce4-session					install
xfce4-settings					install
xfce4-smartbookmark-plugin			install
xfce4-systemload-plugin				install
xfce4-taskmanager				install
xfce4-terminal					install
xfce4-time-out-plugin				install
xfce4-timer-plugin				install
xfce4-verve-plugin				install
xfce4-volumed					install
xfce4-wavelan-plugin				install
xfce4-weather-plugin				install
xfce4-whiskermenu-plugin			install
xfce4-xkb-plugin				install
xfconf						install
xfdesktop4					install
xfdesktop4-data					install
xfonts-base					install
xfonts-encodings				install
xfonts-mathml					install
xfonts-scalable					install
xfonts-utils					install
xfwm4						install
xinit						install
xinput						install
xkb-data					install
xml-core					install
xorg						install
xorg-docs-core					install
xorg-sgml-doctools				install
xpdf						install
xsane						install
xsane-common					install
xscreensaver-data				install
xscreensaver-gl					install
xsel						install
xserver-common					install
xserver-xorg					install
xserver-xorg-core				install
xserver-xorg-input-all				install
xserver-xorg-input-evdev			install
xserver-xorg-input-mouse			install
xserver-xorg-input-synaptics			install
xserver-xorg-input-vmmouse			install
xserver-xorg-input-wacom			install
xserver-xorg-video-all				install
xserver-xorg-video-ati				install
xserver-xorg-video-cirrus			install
xserver-xorg-video-fbdev			install
xserver-xorg-video-glamoregl			install
xserver-xorg-video-intel			install
xserver-xorg-video-mach64			install
xserver-xorg-video-mga				install
xserver-xorg-video-modesetting			install
xserver-xorg-video-neomagic			install
xserver-xorg-video-nouveau			install
xserver-xorg-video-openchrome			install
xserver-xorg-video-qxl				install
xserver-xorg-video-r128				install
xserver-xorg-video-radeon			install
xserver-xorg-video-s3				install
xserver-xorg-video-savage			install
xserver-xorg-video-siliconmotion		install
xserver-xorg-video-sis				install
xserver-xorg-video-sisusb			install
xserver-xorg-video-tdfx				install
xserver-xorg-video-trident			install
xserver-xorg-video-vesa				install
xserver-xorg-video-vmware			install
xterm						install
xtrans-dev					install
xubuntu-artwork					install
xubuntu-community-wallpapers			install
xubuntu-default-settings			install
xubuntu-desktop					install
xubuntu-docs					install
xubuntu-icon-theme				install
xubuntu-wallpapers				install
xul-ext-ubufox					install
xul-ext-unity					install
xul-ext-webaccounts				install
xul-ext-websites-integration			install
xz-utils					install
yelp						install
yelp-xsl					install
youtube-dl					install
zeitgeist					install
zeitgeist-core					install
zeitgeist-datahub				install
zenity						install
zenity-common					install
zip						install
zlib1g:amd64					install
zlib1g:i386					install
zlib1g-dev:amd64				install
