#!/bin/bash

# get current branch in git repo
function parse_git_branch() {
	BRANCH=`git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'`
	if [ ! "${BRANCH}" == "" ]
	then
		STAT=`parse_git_dirty`
		echo "[${BRANCH}${STAT}]"
	else
		echo ""
	fi
}

# get current status of git repo
function parse_git_dirty {
	status=`git status 2>&1 | tee`
	dirty=`echo -n "${status}" 2> /dev/null | grep "modified:" &> /dev/null; echo "$?"`
	untracked=`echo -n "${status}" 2> /dev/null | grep "Untracked files" &> /dev/null; echo "$?"`
	ahead=`echo -n "${status}" 2> /dev/null | grep "Your branch is ahead of" &> /dev/null; echo "$?"`
	newfile=`echo -n "${status}" 2> /dev/null | grep "new file:" &> /dev/null; echo "$?"`
	renamed=`echo -n "${status}" 2> /dev/null | grep "renamed:" &> /dev/null; echo "$?"`
	deleted=`echo -n "${status}" 2> /dev/null | grep "deleted:" &> /dev/null; echo "$?"`
	bits=''
	if [ "${renamed}" == "0" ]; then
		bits=">${bits}"
	fi
	if [ "${ahead}" == "0" ]; then
		bits="*${bits}"
	fi
	if [ "${newfile}" == "0" ]; then
		bits="+${bits}"
	fi
	if [ "${untracked}" == "0" ]; then
		bits="?${bits}"
	fi
	if [ "${deleted}" == "0" ]; then
		bits="x${bits}"
	fi
	if [ "${dirty}" == "0" ]; then
		bits="!${bits}"
	fi
	if [ ! "${bits}" == "" ]; then
		echo " ${bits}"
	else
		echo ""
	fi
}

function nonzero_return() {
	RETVAL=$?
	[ $RETVAL -ne 0 ] && echo "$RETVAL"
}

#Prompt and prompt colors
# 30m - Black
# 31m - Red
# 32m - Green
# 33m - Yellow
# 34m - Blue
# 35m - Purple
# 36m - Cyan
# 37m - White
# 00 - Normal
# 01 - Bold



# hostname
#export PS1="\V [\t] -\`nonzero_return\`- \[\e[37m\]\u\[\e[m\]@\[\e[34m\]\h\[\e[m\]:\[\e[31m\]\w\[\e[m\] \[\e[32m\]\`parse_git_branch\`\[\e[m\]\\$ "

# full qualified domain name
#export PS1="\V [\t] -\`nonzero_return\`- \[\e[37m\]\u\[\e[m\]@\[\e[34m\]\H\[\e[m\]:\[\e[31m\]\w\[\e[m\] \[\e[32m\]\`parse_git_branch\`\[\e[m\]\\$ "

# simple fast
#export PS1="[\t] tty:\l ret:\$? \u@\[\e[34m\]\H\[\e[m\]:\[\e[31m\]\w\[\e[m\]\$ "
# simple fast dimmed
export PS1="\[\e[00;37m\][\t] tty:\l ret:\$? \u@\[\e[0m\]\[\e[00;34m\]\H\[\e[0m\]\[\e[00;37m\]:\[\e[0m\]\[\e[00;31m\]\w\[\e[0m\]\[\e[00;37m\]\\$ \[\e[0m\]"

# standart
#export PS1="${debian_chroot:+($debian_chroot)}\u@\h:\w\$ "

